// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transaction

import (
	"context"

	"github.com/cleitonmarx/symbiont-ai-todoapp/internal/domain/assistant"
	"github.com/cleitonmarx/symbiont-ai-todoapp/internal/domain/outbox"
	"github.com/cleitonmarx/symbiont-ai-todoapp/internal/domain/todo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScope creates a new instance of MockScope. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScope(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScope {
	mock := &MockScope{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScope is an autogenerated mock type for the Scope type
type MockScope struct {
	mock.Mock
}

type MockScope_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScope) EXPECT() *MockScope_Expecter {
	return &MockScope_Expecter{mock: &_m.Mock}
}

// ChatMessage provides a mock function for the type MockScope
func (_mock *MockScope) ChatMessage() assistant.ChatMessageRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChatMessage")
	}

	var r0 assistant.ChatMessageRepository
	if returnFunc, ok := ret.Get(0).(func() assistant.ChatMessageRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(assistant.ChatMessageRepository)
		}
	}
	return r0
}

// MockScope_ChatMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatMessage'
type MockScope_ChatMessage_Call struct {
	*mock.Call
}

// ChatMessage is a helper method to define mock.On call
func (_e *MockScope_Expecter) ChatMessage() *MockScope_ChatMessage_Call {
	return &MockScope_ChatMessage_Call{Call: _e.mock.On("ChatMessage")}
}

func (_c *MockScope_ChatMessage_Call) Run(run func()) *MockScope_ChatMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScope_ChatMessage_Call) Return(chatMessageRepository assistant.ChatMessageRepository) *MockScope_ChatMessage_Call {
	_c.Call.Return(chatMessageRepository)
	return _c
}

func (_c *MockScope_ChatMessage_Call) RunAndReturn(run func() assistant.ChatMessageRepository) *MockScope_ChatMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Conversation provides a mock function for the type MockScope
func (_mock *MockScope) Conversation() assistant.ConversationRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Conversation")
	}

	var r0 assistant.ConversationRepository
	if returnFunc, ok := ret.Get(0).(func() assistant.ConversationRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(assistant.ConversationRepository)
		}
	}
	return r0
}

// MockScope_Conversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Conversation'
type MockScope_Conversation_Call struct {
	*mock.Call
}

// Conversation is a helper method to define mock.On call
func (_e *MockScope_Expecter) Conversation() *MockScope_Conversation_Call {
	return &MockScope_Conversation_Call{Call: _e.mock.On("Conversation")}
}

func (_c *MockScope_Conversation_Call) Run(run func()) *MockScope_Conversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScope_Conversation_Call) Return(conversationRepository assistant.ConversationRepository) *MockScope_Conversation_Call {
	_c.Call.Return(conversationRepository)
	return _c
}

func (_c *MockScope_Conversation_Call) RunAndReturn(run func() assistant.ConversationRepository) *MockScope_Conversation_Call {
	_c.Call.Return(run)
	return _c
}

// ConversationSummary provides a mock function for the type MockScope
func (_mock *MockScope) ConversationSummary() assistant.ConversationSummaryRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConversationSummary")
	}

	var r0 assistant.ConversationSummaryRepository
	if returnFunc, ok := ret.Get(0).(func() assistant.ConversationSummaryRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(assistant.ConversationSummaryRepository)
		}
	}
	return r0
}

// MockScope_ConversationSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConversationSummary'
type MockScope_ConversationSummary_Call struct {
	*mock.Call
}

// ConversationSummary is a helper method to define mock.On call
func (_e *MockScope_Expecter) ConversationSummary() *MockScope_ConversationSummary_Call {
	return &MockScope_ConversationSummary_Call{Call: _e.mock.On("ConversationSummary")}
}

func (_c *MockScope_ConversationSummary_Call) Run(run func()) *MockScope_ConversationSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScope_ConversationSummary_Call) Return(conversationSummaryRepository assistant.ConversationSummaryRepository) *MockScope_ConversationSummary_Call {
	_c.Call.Return(conversationSummaryRepository)
	return _c
}

func (_c *MockScope_ConversationSummary_Call) RunAndReturn(run func() assistant.ConversationSummaryRepository) *MockScope_ConversationSummary_Call {
	_c.Call.Return(run)
	return _c
}

// Outbox provides a mock function for the type MockScope
func (_mock *MockScope) Outbox() outbox.Repository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Outbox")
	}

	var r0 outbox.Repository
	if returnFunc, ok := ret.Get(0).(func() outbox.Repository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(outbox.Repository)
		}
	}
	return r0
}

// MockScope_Outbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Outbox'
type MockScope_Outbox_Call struct {
	*mock.Call
}

// Outbox is a helper method to define mock.On call
func (_e *MockScope_Expecter) Outbox() *MockScope_Outbox_Call {
	return &MockScope_Outbox_Call{Call: _e.mock.On("Outbox")}
}

func (_c *MockScope_Outbox_Call) Run(run func()) *MockScope_Outbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScope_Outbox_Call) Return(repository outbox.Repository) *MockScope_Outbox_Call {
	_c.Call.Return(repository)
	return _c
}

func (_c *MockScope_Outbox_Call) RunAndReturn(run func() outbox.Repository) *MockScope_Outbox_Call {
	_c.Call.Return(run)
	return _c
}

// Todo provides a mock function for the type MockScope
func (_mock *MockScope) Todo() todo.Repository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Todo")
	}

	var r0 todo.Repository
	if returnFunc, ok := ret.Get(0).(func() todo.Repository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(todo.Repository)
		}
	}
	return r0
}

// MockScope_Todo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Todo'
type MockScope_Todo_Call struct {
	*mock.Call
}

// Todo is a helper method to define mock.On call
func (_e *MockScope_Expecter) Todo() *MockScope_Todo_Call {
	return &MockScope_Todo_Call{Call: _e.mock.On("Todo")}
}

func (_c *MockScope_Todo_Call) Run(run func()) *MockScope_Todo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScope_Todo_Call) Return(repository todo.Repository) *MockScope_Todo_Call {
	_c.Call.Return(repository)
	return _c
}

func (_c *MockScope_Todo_Call) RunAndReturn(run func() todo.Repository) *MockScope_Todo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Execute(ctx context.Context, fn func(ctx context.Context, scope Scope) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context, scope Scope) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUnitOfWork_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context, scope Scope) error
func (_e *MockUnitOfWork_Expecter) Execute(ctx interface{}, fn interface{}) *MockUnitOfWork_Execute_Call {
	return &MockUnitOfWork_Execute_Call{Call: _e.mock.On("Execute", ctx, fn)}
}

func (_c *MockUnitOfWork_Execute_Call) Run(run func(ctx context.Context, fn func(ctx context.Context, scope Scope) error)) *MockUnitOfWork_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context, scope Scope) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, scope Scope) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Execute_Call) Return(err error) *MockUnitOfWork_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Execute_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context, scope Scope) error) error) *MockUnitOfWork_Execute_Call {
	_c.Call.Return(run)
	return _c
}
