// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package todo

import (
	"context"
	"time"

	"github.com/cleitonmarx/symbiont-ai-todoapp/internal/domain/todo"
	"github.com/cleitonmarx/symbiont-ai-todoapp/internal/domain/transaction"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreate creates a new instance of MockCreate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreate {
	mock := &MockCreate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreate is an autogenerated mock type for the Create type
type MockCreate struct {
	mock.Mock
}

type MockCreate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreate) EXPECT() *MockCreate_Expecter {
	return &MockCreate_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCreate
func (_mock *MockCreate) Execute(ctx context.Context, title string, dueDate time.Time) (todo.Todo, error) {
	ret := _mock.Called(ctx, title, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) (todo.Todo, error)); ok {
		return returnFunc(ctx, title, dueDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) todo.Todo); ok {
		r0 = returnFunc(ctx, title, dueDate)
	} else {
		r0 = ret.Get(0).(todo.Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, title, dueDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreate_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCreate_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - dueDate time.Time
func (_e *MockCreate_Expecter) Execute(ctx interface{}, title interface{}, dueDate interface{}) *MockCreate_Execute_Call {
	return &MockCreate_Execute_Call{Call: _e.mock.On("Execute", ctx, title, dueDate)}
}

func (_c *MockCreate_Execute_Call) Run(run func(ctx context.Context, title string, dueDate time.Time)) *MockCreate_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCreate_Execute_Call) Return(todo1 todo.Todo, err error) *MockCreate_Execute_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockCreate_Execute_Call) RunAndReturn(run func(ctx context.Context, title string, dueDate time.Time) (todo.Todo, error)) *MockCreate_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreator creates a new instance of MockCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreator {
	mock := &MockCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreator is an autogenerated mock type for the Creator type
type MockCreator struct {
	mock.Mock
}

type MockCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreator) EXPECT() *MockCreator_Expecter {
	return &MockCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCreator
func (_mock *MockCreator) Create(ctx context.Context, scope transaction.Scope, title string, dueDate time.Time) (todo.Todo, error) {
	ret := _mock.Called(ctx, scope, title, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, transaction.Scope, string, time.Time) (todo.Todo, error)); ok {
		return returnFunc(ctx, scope, title, dueDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, transaction.Scope, string, time.Time) todo.Todo); ok {
		r0 = returnFunc(ctx, scope, title, dueDate)
	} else {
		r0 = ret.Get(0).(todo.Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, transaction.Scope, string, time.Time) error); ok {
		r1 = returnFunc(ctx, scope, title, dueDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - scope transaction.Scope
//   - title string
//   - dueDate time.Time
func (_e *MockCreator_Expecter) Create(ctx interface{}, scope interface{}, title interface{}, dueDate interface{}) *MockCreator_Create_Call {
	return &MockCreator_Create_Call{Call: _e.mock.On("Create", ctx, scope, title, dueDate)}
}

func (_c *MockCreator_Create_Call) Run(run func(ctx context.Context, scope transaction.Scope, title string, dueDate time.Time)) *MockCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 transaction.Scope
		if args[1] != nil {
			arg1 = args[1].(transaction.Scope)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCreator_Create_Call) Return(todo1 todo.Todo, err error) *MockCreator_Create_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockCreator_Create_Call) RunAndReturn(run func(ctx context.Context, scope transaction.Scope, title string, dueDate time.Time) (todo.Todo, error)) *MockCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDelete creates a new instance of MockDelete. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDelete(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDelete {
	mock := &MockDelete{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDelete is an autogenerated mock type for the Delete type
type MockDelete struct {
	mock.Mock
}

type MockDelete_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDelete) EXPECT() *MockDelete_Expecter {
	return &MockDelete_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockDelete
func (_mock *MockDelete) Execute(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDelete_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDelete_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDelete_Expecter) Execute(ctx interface{}, id interface{}) *MockDelete_Execute_Call {
	return &MockDelete_Execute_Call{Call: _e.mock.On("Execute", ctx, id)}
}

func (_c *MockDelete_Execute_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDelete_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDelete_Execute_Call) Return(err error) *MockDelete_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDelete_Execute_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockDelete_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleter creates a new instance of MockDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleter {
	mock := &MockDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeleter is an autogenerated mock type for the Deleter type
type MockDeleter struct {
	mock.Mock
}

type MockDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleter) EXPECT() *MockDeleter_Expecter {
	return &MockDeleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockDeleter
func (_mock *MockDeleter) Delete(ctx context.Context, scope transaction.Scope, id uuid.UUID) error {
	ret := _mock.Called(ctx, scope, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, transaction.Scope, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, scope, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - scope transaction.Scope
//   - id uuid.UUID
func (_e *MockDeleter_Expecter) Delete(ctx interface{}, scope interface{}, id interface{}) *MockDeleter_Delete_Call {
	return &MockDeleter_Delete_Call{Call: _e.mock.On("Delete", ctx, scope, id)}
}

func (_c *MockDeleter_Delete_Call) Run(run func(ctx context.Context, scope transaction.Scope, id uuid.UUID)) *MockDeleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 transaction.Scope
		if args[1] != nil {
			arg1 = args[1].(transaction.Scope)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeleter_Delete_Call) Return(err error) *MockDeleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeleter_Delete_Call) RunAndReturn(run func(ctx context.Context, scope transaction.Scope, id uuid.UUID) error) *MockDeleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockList creates a new instance of MockList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockList(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockList {
	mock := &MockList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockList is an autogenerated mock type for the List type
type MockList struct {
	mock.Mock
}

type MockList_Expecter struct {
	mock *mock.Mock
}

func (_m *MockList) EXPECT() *MockList_Expecter {
	return &MockList_Expecter{mock: &_m.Mock}
}

// Query provides a mock function for the type MockList
func (_mock *MockList) Query(ctx context.Context, page int, pageSize int, opts ...ListOptions) ([]todo.Todo, bool, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, page, pageSize, opts)
	} else {
		tmpRet = _mock.Called(ctx, page, pageSize)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []todo.Todo
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, ...ListOptions) ([]todo.Todo, bool, error)); ok {
		return returnFunc(ctx, page, pageSize, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, ...ListOptions) []todo.Todo); ok {
		r0 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]todo.Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, ...ListOptions) bool); ok {
		r1 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int, ...ListOptions) error); ok {
		r2 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockList_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockList_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
//   - opts ...ListTodoOptions
func (_e *MockList_Expecter) Query(ctx interface{}, page interface{}, pageSize interface{}, opts ...interface{}) *MockList_Query_Call {
	return &MockList_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, page, pageSize}, opts...)...)}
}

func (_c *MockList_Query_Call) Run(run func(ctx context.Context, page int, pageSize int, opts ...ListOptions)) *MockList_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []ListOptions
		var variadicArgs []ListOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]ListOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockList_Query_Call) Return(todos []todo.Todo, b bool, err error) *MockList_Query_Call {
	_c.Call.Return(todos, b, err)
	return _c
}

func (_c *MockList_Query_Call) RunAndReturn(run func(ctx context.Context, page int, pageSize int, opts ...ListOptions) ([]todo.Todo, bool, error)) *MockList_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdate creates a new instance of MockUpdate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdate {
	mock := &MockUpdate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdate is an autogenerated mock type for the Update type
type MockUpdate struct {
	mock.Mock
}

type MockUpdate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdate) EXPECT() *MockUpdate_Expecter {
	return &MockUpdate_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockUpdate
func (_mock *MockUpdate) Execute(ctx context.Context, id uuid.UUID, title *string, status *todo.Status, dueDate *time.Time) (todo.Todo, error) {
	ret := _mock.Called(ctx, id, title, status, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *todo.Status, *time.Time) (todo.Todo, error)); ok {
		return returnFunc(ctx, id, title, status, dueDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *string, *todo.Status, *time.Time) todo.Todo); ok {
		r0 = returnFunc(ctx, id, title, status, dueDate)
	} else {
		r0 = ret.Get(0).(todo.Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *string, *todo.Status, *time.Time) error); ok {
		r1 = returnFunc(ctx, id, title, status, dueDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdate_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdate_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - title *string
//   - status *todo.Status
//   - dueDate *time.Time
func (_e *MockUpdate_Expecter) Execute(ctx interface{}, id interface{}, title interface{}, status interface{}, dueDate interface{}) *MockUpdate_Execute_Call {
	return &MockUpdate_Execute_Call{Call: _e.mock.On("Execute", ctx, id, title, status, dueDate)}
}

func (_c *MockUpdate_Execute_Call) Run(run func(ctx context.Context, id uuid.UUID, title *string, status *todo.Status, dueDate *time.Time)) *MockUpdate_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *todo.Status
		if args[3] != nil {
			arg3 = args[3].(*todo.Status)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUpdate_Execute_Call) Return(todo1 todo.Todo, err error) *MockUpdate_Execute_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockUpdate_Execute_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, title *string, status *todo.Status, dueDate *time.Time) (todo.Todo, error)) *MockUpdate_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdater creates a new instance of MockUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdater {
	mock := &MockUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdater is an autogenerated mock type for the Updater type
type MockUpdater struct {
	mock.Mock
}

type MockUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdater) EXPECT() *MockUpdater_Expecter {
	return &MockUpdater_Expecter{mock: &_m.Mock}
}

// Update provides a mock function for the type MockUpdater
func (_mock *MockUpdater) Update(ctx context.Context, scope transaction.Scope, id uuid.UUID, title *string, status *todo.Status, dueDate *time.Time) (todo.Todo, error) {
	ret := _mock.Called(ctx, scope, id, title, status, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 todo.Todo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, transaction.Scope, uuid.UUID, *string, *todo.Status, *time.Time) (todo.Todo, error)); ok {
		return returnFunc(ctx, scope, id, title, status, dueDate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, transaction.Scope, uuid.UUID, *string, *todo.Status, *time.Time) todo.Todo); ok {
		r0 = returnFunc(ctx, scope, id, title, status, dueDate)
	} else {
		r0 = ret.Get(0).(todo.Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, transaction.Scope, uuid.UUID, *string, *todo.Status, *time.Time) error); ok {
		r1 = returnFunc(ctx, scope, id, title, status, dueDate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - scope transaction.Scope
//   - id uuid.UUID
//   - title *string
//   - status *todo.Status
//   - dueDate *time.Time
func (_e *MockUpdater_Expecter) Update(ctx interface{}, scope interface{}, id interface{}, title interface{}, status interface{}, dueDate interface{}) *MockUpdater_Update_Call {
	return &MockUpdater_Update_Call{Call: _e.mock.On("Update", ctx, scope, id, title, status, dueDate)}
}

func (_c *MockUpdater_Update_Call) Run(run func(ctx context.Context, scope transaction.Scope, id uuid.UUID, title *string, status *todo.Status, dueDate *time.Time)) *MockUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 transaction.Scope
		if args[1] != nil {
			arg1 = args[1].(transaction.Scope)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *todo.Status
		if args[4] != nil {
			arg4 = args[4].(*todo.Status)
		}
		var arg5 *time.Time
		if args[5] != nil {
			arg5 = args[5].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockUpdater_Update_Call) Return(todo1 todo.Todo, err error) *MockUpdater_Update_Call {
	_c.Call.Return(todo1, err)
	return _c
}

func (_c *MockUpdater_Update_Call) RunAndReturn(run func(ctx context.Context, scope transaction.Scope, id uuid.UUID, title *string, status *todo.Status, dueDate *time.Time) (todo.Todo, error)) *MockUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}
