package integration

import (
	"testing"
	"time"

	rest "github.com/cleitonmarx/symbiont-ai-todoapp/internal/adapters/inbound/http/gen"
	"github.com/oapi-codegen/runtime/types"
	"github.com/stretchr/testify/require"
)

func TestCTT(t *testing.T) {
	// 100 sample todos with meaningful, searchable titles and different due dates, all OPEN
	// You can use this slice for seeding or testing.

	todos := []rest.CreateTodoRequest{
		{Title: "Buy groceries", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 1)}},
		{Title: "Finish project report", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 2)}},
		{Title: "Call Alice about meeting", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 3)}},
		{Title: "Schedule dentist appointment", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 4)}},
		{Title: "Book flight tickets to NYC", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 5)}},
		{Title: "Prepare for Monday presentation", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 6)}},
		{Title: "Renew car insurance", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 7)}},
		{Title: "Submit tax documents", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 8)}},
		{Title: "Organize home office", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 9)}},
		{Title: "Read 'Deep Work' book", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 10)}},
		{Title: "Update LinkedIn profile", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 11)}},
		{Title: "Plan weekend hiking trip", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 12)}},
		{Title: "Clean out garage", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 13)}},
		{Title: "Backup laptop files", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 14)}},
		{Title: "Research new laptop models", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 15)}},
		{Title: "Pay electricity bill", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 16)}},
		{Title: "Arrange birthday party for Sam", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 17)}},
		{Title: "Order new running shoes", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 18)}},
		{Title: "Write blog post on productivity", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 19)}},
		{Title: "Practice guitar for 30 minutes", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 20)}},
		{Title: "Update project roadmap", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 21)}},
		{Title: "Review quarterly budget", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 22)}},
		{Title: "Send thank you notes", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 23)}},
		{Title: "Fix leaky kitchen faucet", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 24)}},
		{Title: "Prepare for coding interview", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 25)}},
		{Title: "Organize photo album", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 26)}},
		{Title: "Update resume", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 27)}},
		{Title: "Research investment options", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 28)}},
		{Title: "Plan family vacation", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 29)}},
		{Title: "Buy birthday gift for Emma", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 30)}},
		{Title: "Attend online marketing webinar", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 31)}},
		{Title: "Set up home Wi-Fi network", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 32)}},
		{Title: "Read 'Atomic Habits'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 33)}},
		{Title: "Organize bookshelf", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 34)}},
		{Title: "Schedule annual health checkup", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 35)}},
		{Title: "Clean windows", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 36)}},
		{Title: "Write thank you email to mentor", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 37)}},
		{Title: "Practice meditation", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 38)}},
		{Title: "Update household budget", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 39)}},
		{Title: "Buy groceries for the week", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 40)}},
		{Title: "Fix bike tire", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 41)}},
		{Title: "Plan team meeting agenda", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 42)}},
		{Title: "Organize digital files", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 43)}},
		{Title: "Read industry news", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 44)}},
		{Title: "Prepare for book club", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 45)}},
		{Title: "Update emergency contacts", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 46)}},
		{Title: "Clean out email inbox", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 47)}},
		{Title: "Research online courses", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 48)}},
		{Title: "Buy new headphones", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 49)}},
		{Title: "Schedule eye exam", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 50)}},
		{Title: "Organize kitchen pantry", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 51)}},
		{Title: "Write monthly newsletter", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 52)}},
		{Title: "Plan charity event", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 53)}},
		{Title: "Update website portfolio", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 54)}},
		{Title: "Clean car interior", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 55)}},
		{Title: "Buy pet food", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 56)}},
		{Title: "Practice Spanish vocabulary", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 57)}},
		{Title: "Organize closet", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 58)}},
		{Title: "Read 'Clean Code'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 59)}},
		{Title: "Schedule parent-teacher meeting", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 60)}},
		{Title: "Update insurance policy", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 61)}},
		{Title: "Plan weekend getaway", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 62)}},
		{Title: "Fix broken shelf", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 63)}},
		{Title: "Write thank you card", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 64)}},
		{Title: "Organize garden tools", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 65)}},
		{Title: "Buy new backpack", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 66)}},
		{Title: "Research healthy recipes", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 67)}},
		{Title: "Clean bathroom", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 68)}},
		{Title: "Update phone contacts", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 69)}},
		{Title: "Plan study schedule", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 70)}},
		{Title: "Buy new phone charger", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 71)}},
		{Title: "Organize travel documents", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 72)}},
		{Title: "Read 'The Pragmatic Programmer'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 73)}},
		{Title: "Clean living room", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 74)}},
		{Title: "Update LinkedIn connections", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 75)}},
		{Title: "Plan team lunch", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 76)}},
		{Title: "Buy new water bottle", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 77)}},
		{Title: "Organize receipts", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 78)}},
		{Title: "Read 'Design Patterns'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 79)}},
		{Title: "Schedule car maintenance", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 80)}},
		{Title: "Clean out fridge", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 81)}},
		{Title: "Write cover letter", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 82)}},
		{Title: "Plan birthday dinner", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 83)}},
		{Title: "Buy new planner", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 84)}},
		{Title: "Organize digital photos", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 85)}},
		{Title: "Read 'Refactoring'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 86)}},
		{Title: "Schedule vet appointment", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 87)}},
		{Title: "Clean patio", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 88)}},
		{Title: "Update emergency kit", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 89)}},
		{Title: "Buy new shoes", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 90)}},
		{Title: "Organize music playlist", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 91)}},
		{Title: "Read 'The Clean Coder'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 92)}},
		{Title: "Plan weekend picnic", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 93)}},
		{Title: "Buy new lamp", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 94)}},
		{Title: "Organize sports equipment", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 95)}},
		{Title: "Read 'Effective Java'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 96)}},
		{Title: "Schedule dentist cleaning", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 97)}},
		{Title: "Clean bedroom", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 98)}},
		{Title: "Update family calendar", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 99)}},
		{Title: "Buy new coffee maker", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 100)}},
		{Title: "Write unit tests for API", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 101)}},
		{Title: "Organize team building activity", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 102)}},
		{Title: "Buy anniversary gift", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 103)}},
		{Title: "Schedule oil change", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 104)}},
		{Title: "Read 'Go Programming Language'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 105)}},
		{Title: "Clean attic", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 106)}},
		{Title: "Update project documentation", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 107)}},
		{Title: "Plan surprise party", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 108)}},
		{Title: "Buy new desk chair", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 109)}},
		{Title: "Organize code review session", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 110)}},
		{Title: "Schedule annual eye checkup", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 111)}},
		{Title: "Read 'You Don't Know JS'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 112)}},
		{Title: "Clean out storage unit", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 113)}},
		{Title: "Update social media bios", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 114)}},
		{Title: "Buy new monitor", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 115)}},
		{Title: "Plan holiday decorations", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 116)}},
		{Title: "Organize recipe collection", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 117)}},
		{Title: "Write thank you speech", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 118)}},
		{Title: "Schedule HVAC maintenance", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 119)}},
		{Title: "Buy new suitcase", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 120)}},
		{Title: "Organize art supplies", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 121)}},
		{Title: "Read 'Cracking the Coding Interview'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 122)}},
		{Title: "Clean out medicine cabinet", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 123)}},
		{Title: "Update emergency plan", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 124)}},
		{Title: "Buy new winter coat", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 125)}},
		{Title: "Plan weekend road trip", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 126)}},
		{Title: "Organize board games", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 127)}},
		{Title: "Write product review", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 128)}},
		{Title: "Schedule plumbing inspection", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 129)}},
		{Title: "Buy new sunglasses", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 130)}},
		{Title: "Organize movie collection", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 131)}},
		{Title: "Read 'The Art of Computer Programming'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 132)}},
		{Title: "Clean out car trunk", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 133)}},
		{Title: "Update travel itinerary", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 134)}},
		{Title: "Buy new wallet", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 135)}},
		{Title: "Plan family game night", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 136)}},
		{Title: "Organize craft supplies", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 137)}},
		{Title: "Write guest blog post", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 138)}},
		{Title: "Schedule chimney cleaning", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 139)}},
		{Title: "Buy new headphones for gym", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 140)}},
		{Title: "Organize digital backups", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 141)}},
		{Title: "Read 'Introduction to Algorithms'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 142)}},
		{Title: "Clean out garden shed", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 143)}},
		{Title: "Update pet vaccination records", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 144)}},
		{Title: "Buy new yoga mat", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 145)}},
		{Title: "Plan monthly meal prep", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 146)}},
		{Title: "Organize tax receipts", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 147)}},
		{Title: "Write LinkedIn recommendation", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 148)}},
		{Title: "Schedule roof inspection", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 149)}},
		{Title: "Buy new hiking boots", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 150)}},
		{Title: "Organize music library", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 151)}},
		{Title: "Read 'Refactoring UI'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 152)}},
		{Title: "Clean out freezer", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 153)}},
		{Title: "Update software licenses", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 154)}},
		{Title: "Buy new kitchen knives", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 155)}},
		{Title: "Plan spring cleaning", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 156)}},
		{Title: "Organize travel souvenirs", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 157)}},
		{Title: "Write conference summary", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 158)}},
		{Title: "Schedule pest control", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 159)}},
		{Title: "Buy new running shorts", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 160)}},
		{Title: "Organize pantry staples", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 161)}},
		{Title: "Read 'Continuous Delivery'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 162)}},
		{Title: "Clean out attic", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 163)}},
		{Title: "Update family tree", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 164)}},
		{Title: "Buy new garden hose", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 165)}},
		{Title: "Plan summer barbecue", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 166)}},
		{Title: "Organize digital artwork", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 167)}},
		{Title: "Write product feedback", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 168)}},
		{Title: "Schedule dental x-rays", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 169)}},
		{Title: "Buy new umbrella", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 170)}},
		{Title: "Organize home gym", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 171)}},
		{Title: "Read 'Domain-Driven Design'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 172)}},
		{Title: "Clean out laundry room", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 173)}},
		{Title: "Update medical records", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 174)}},
		{Title: "Buy new pillows", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 175)}},
		{Title: "Plan winter vacation", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 176)}},
		{Title: "Organize sewing supplies", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 177)}},
		{Title: "Write thank you letter", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 178)}},
		{Title: "Schedule annual physical", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 179)}},
		{Title: "Buy new coffee grinder", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 180)}},
		{Title: "Organize family photos", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 181)}},
		{Title: "Read 'The Mythical Man-Month'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 182)}},
		{Title: "Clean out fireplace", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 183)}},
		{Title: "Update car registration", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 184)}},
		{Title: "Buy new suitcase tags", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 185)}},
		{Title: "Plan birthday surprise", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 186)}},
		{Title: "Organize knitting supplies", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 187)}},
		{Title: "Write project proposal", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 188)}},
		{Title: "Schedule home security check", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 189)}},
		{Title: "Buy new lunchbox", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 190)}},
		{Title: "Organize digital passwords", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 191)}},
		{Title: "Read 'Patterns of Enterprise Application Architecture'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 192)}},
		{Title: "Clean out tool box", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 193)}},
		{Title: "Update home inventory", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 194)}},
		{Title: "Buy new water filter", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 195)}},
		{Title: "Plan neighborhood potluck", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 196)}},
		{Title: "Organize camping gear", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 197)}},
		{Title: "Write event invitation", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 198)}},
		{Title: "Schedule annual flu shot", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 199)}},
		{Title: "Buy new slippers", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 200)}},
		{Title: "Renew passport", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 201)}},
		{Title: "Organize holiday photos", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 202)}},
		{Title: "Buy new bicycle helmet", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 203)}},
		{Title: "Schedule annual dental checkup", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 204)}},
		{Title: "Write thank you note to teacher", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 205)}},
		{Title: "Plan weekend camping trip", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 206)}},
		{Title: "Update emergency contact list", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 207)}},
		{Title: "Clean out attic storage", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 208)}},
		{Title: "Buy new tennis racket", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 209)}},
		{Title: "Organize digital music files", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 210)}},
		{Title: "Read 'The Lean Startup'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 211)}},
		{Title: "Schedule annual eye exam", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 212)}},
		{Title: "Buy new winter boots", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 213)}},
		{Title: "Plan family reunion", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 214)}},
		{Title: "Organize kitchen drawers", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 215)}},
		{Title: "Write book summary", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 216)}},
		{Title: "Schedule annual HVAC check", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 217)}},
		{Title: "Buy new gym bag", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 218)}},
		{Title: "Organize paperwork", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 219)}},
		{Title: "Read 'Test-Driven Development'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 220)}},
		{Title: "Plan garden layout", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 221)}},
		{Title: "Clean out basement", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 222)}},
		{Title: "Update will and testament", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 223)}},
		{Title: "Buy new reading lamp", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 224)}},
		{Title: "Organize spice rack", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 225)}},
		{Title: "Write travel blog post", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 226)}},
		{Title: "Schedule chimney inspection", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 227)}},
		{Title: "Buy new running shoes", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 228)}},
		{Title: "Plan birthday party for Alex", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 229)}},
		{Title: "Organize laundry supplies", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 230)}},
		{Title: "Read 'The Phoenix Project'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 231)}},
		{Title: "Clean out glove compartment", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 232)}},
		{Title: "Update LinkedIn summary", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 233)}},
		{Title: "Buy new headphones for work", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 234)}},
		{Title: "Plan monthly budget", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 235)}},
		{Title: "Organize pet supplies", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 236)}},
		{Title: "Write thank you email to client", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 237)}},
		{Title: "Schedule annual car inspection", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 238)}},
		{Title: "Buy new office chair", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 239)}},
		{Title: "Plan weekend road trip with friends", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 240)}},
		{Title: "Organize digital receipts", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 241)}},
		{Title: "Read 'Clean Architecture'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 242)}},
		{Title: "Clean out kitchen cabinets", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 243)}},
		{Title: "Update emergency evacuation plan", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 244)}},
		{Title: "Buy new hiking backpack", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 245)}},
		{Title: "Plan summer vacation", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 246)}},
		{Title: "Organize home library", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 247)}},
		{Title: "Write product manual", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 248)}},
		{Title: "Schedule annual physical exam", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 249)}},
		{Title: "Buy new garden tools", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 250)}},
		{Title: "Plan family photo shoot", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 251)}},
		{Title: "Organize digital notes", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 252)}},
		{Title: "Read 'Extreme Programming Explained'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 253)}},
		{Title: "Clean out storage closet", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 254)}},
		{Title: "Update insurance information", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 255)}},
		{Title: "Buy new lunch bag", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 256)}},
		{Title: "Plan weekend getaway with partner", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 257)}},
		{Title: "Organize craft room", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 258)}},
		{Title: "Write thank you card to neighbor", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 259)}},
		{Title: "Schedule annual pest inspection", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 260)}},
		{Title: "Buy new kitchen towels", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 261)}},
		{Title: "Plan birthday dinner for mom", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 262)}},
		{Title: "Organize digital bookmarks", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 263)}},
		{Title: "Read 'The DevOps Handbook'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 264)}},
		{Title: "Clean out garage attic", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 265)}},
		{Title: "Update pet microchip info", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 266)}},
		{Title: "Buy new water bottle for gym", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 267)}},
		{Title: "Plan weekend hike", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 268)}},
		{Title: "Organize family recipes", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 269)}},
		{Title: "Write blog post on remote work", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 270)}},
		{Title: "Schedule annual eye screening", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 271)}},
		{Title: "Buy new phone case", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 272)}},
		{Title: "Plan spring garden", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 273)}},
		{Title: "Organize digital calendar", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 274)}},
		{Title: "Read 'Soft Skills'", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 275)}},
		{Title: "Clean out coat closet", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 276)}},
		{Title: "Update emergency supplies", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 277)}},
		{Title: "Buy new backpack for school", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 278)}},
		{Title: "Plan weekend brunch", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 279)}},
		{Title: "Organize digital contacts", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 280)}},
		{Title: "Write thank you letter to friend", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 281)}},
		{Title: "Schedule annual roof cleaning", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 282)}},
		{Title: "Buy new kitchen scale", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 283)}},
		{Title: "Plan family movie night", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 284)}},
		{Title: "Organize digital documents", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 285)}},
		{Title: "Read 'Inspired' by Marty Cagan", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 286)}},
		{Title: "Clean out pantry shelves", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 287)}},
		{Title: "Update family medical history", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 288)}},
		{Title: "Buy new yoga block", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 289)}},
		{Title: "Plan weekend bike ride", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 290)}},
		{Title: "Organize digital photos by year", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 291)}},
		{Title: "Write product suggestion", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 292)}},
		{Title: "Schedule annual septic inspection", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 293)}},
		{Title: "Buy new lunch container", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 294)}},
		{Title: "Plan summer reading list", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 295)}},
		{Title: "Organize digital music playlists", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 296)}},
		{Title: "Read 'Drive' by Daniel Pink", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 297)}},
		{Title: "Clean out shoe rack", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 298)}},
		{Title: "Update home maintenance log", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 299)}},
		{Title: "Buy new reusable grocery bags", DueDate: types.Date{Time: time.Now().AddDate(0, 0, 300)}},
	}

	cli, _ := rest.NewClientWithResponses("http://localhost:8080")

	for _, todo := range todos {
		// Use the todo item as needed for seeding or testing
		_, err := cli.CreateTodoWithResponse(t.Context(), todo)
		require.NoError(t, err, "failed to create todo: %v", todo.Title)
	}
}
