// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package todo

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateTodo provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateTodo(ctx context.Context, todo Todo) error {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Todo) error); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodo'
type MockRepository_CreateTodo_Call struct {
	*mock.Call
}

// CreateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todo Todo
func (_e *MockRepository_Expecter) CreateTodo(ctx interface{}, todo interface{}) *MockRepository_CreateTodo_Call {
	return &MockRepository_CreateTodo_Call{Call: _e.mock.On("CreateTodo", ctx, todo)}
}

func (_c *MockRepository_CreateTodo_Call) Run(run func(ctx context.Context, todo Todo)) *MockRepository_CreateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Todo
		if args[1] != nil {
			arg1 = args[1].(Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateTodo_Call) Return(err error) *MockRepository_CreateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateTodo_Call) RunAndReturn(run func(ctx context.Context, todo Todo) error) *MockRepository_CreateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTodo provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteTodo(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTodo'
type MockRepository_DeleteTodo_Call struct {
	*mock.Call
}

// DeleteTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) DeleteTodo(ctx interface{}, id interface{}) *MockRepository_DeleteTodo_Call {
	return &MockRepository_DeleteTodo_Call{Call: _e.mock.On("DeleteTodo", ctx, id)}
}

func (_c *MockRepository_DeleteTodo_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_DeleteTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteTodo_Call) Return(err error) *MockRepository_DeleteTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteTodo_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockRepository_DeleteTodo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodo provides a mock function for the type MockRepository
func (_mock *MockRepository) GetTodo(ctx context.Context, id uuid.UUID) (Todo, bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTodo")
	}

	var r0 Todo
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (Todo, bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) Todo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Todo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodo'
type MockRepository_GetTodo_Call struct {
	*mock.Call
}

// GetTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetTodo(ctx interface{}, id interface{}) *MockRepository_GetTodo_Call {
	return &MockRepository_GetTodo_Call{Call: _e.mock.On("GetTodo", ctx, id)}
}

func (_c *MockRepository_GetTodo_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetTodo_Call) Return(todo Todo, b bool, err error) *MockRepository_GetTodo_Call {
	_c.Call.Return(todo, b, err)
	return _c
}

func (_c *MockRepository_GetTodo_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (Todo, bool, error)) *MockRepository_GetTodo_Call {
	_c.Call.Return(run)
	return _c
}

// ListTodos provides a mock function for the type MockRepository
func (_mock *MockRepository) ListTodos(ctx context.Context, page int, pageSize int, opts ...ListOption) ([]Todo, bool, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, page, pageSize, opts)
	} else {
		tmpRet = _mock.Called(ctx, page, pageSize)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListTodos")
	}

	var r0 []Todo
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, ...ListOption) ([]Todo, bool, error)); ok {
		return returnFunc(ctx, page, pageSize, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, ...ListOption) []Todo); ok {
		r0 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Todo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, ...ListOption) bool); ok {
		r1 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int, ...ListOption) error); ok {
		r2 = returnFunc(ctx, page, pageSize, opts...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_ListTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTodos'
type MockRepository_ListTodos_Call struct {
	*mock.Call
}

// ListTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
//   - opts ...ListOption
func (_e *MockRepository_Expecter) ListTodos(ctx interface{}, page interface{}, pageSize interface{}, opts ...interface{}) *MockRepository_ListTodos_Call {
	return &MockRepository_ListTodos_Call{Call: _e.mock.On("ListTodos",
		append([]interface{}{ctx, page, pageSize}, opts...)...)}
}

func (_c *MockRepository_ListTodos_Call) Run(run func(ctx context.Context, page int, pageSize int, opts ...ListOption)) *MockRepository_ListTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 []ListOption
		var variadicArgs []ListOption
		if len(args) > 3 {
			variadicArgs = args[3].([]ListOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockRepository_ListTodos_Call) Return(todos []Todo, b bool, err error) *MockRepository_ListTodos_Call {
	_c.Call.Return(todos, b, err)
	return _c
}

func (_c *MockRepository_ListTodos_Call) RunAndReturn(run func(ctx context.Context, page int, pageSize int, opts ...ListOption) ([]Todo, bool, error)) *MockRepository_ListTodos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTodo provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateTodo(ctx context.Context, todo Todo) error {
	ret := _mock.Called(ctx, todo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Todo) error); ok {
		r0 = returnFunc(ctx, todo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTodo'
type MockRepository_UpdateTodo_Call struct {
	*mock.Call
}

// UpdateTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - todo Todo
func (_e *MockRepository_Expecter) UpdateTodo(ctx interface{}, todo interface{}) *MockRepository_UpdateTodo_Call {
	return &MockRepository_UpdateTodo_Call{Call: _e.mock.On("UpdateTodo", ctx, todo)}
}

func (_c *MockRepository_UpdateTodo_Call) Run(run func(ctx context.Context, todo Todo)) *MockRepository_UpdateTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Todo
		if args[1] != nil {
			arg1 = args[1].(Todo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateTodo_Call) Return(err error) *MockRepository_UpdateTodo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateTodo_Call) RunAndReturn(run func(ctx context.Context, todo Todo) error) *MockRepository_UpdateTodo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBoardSummaryRepository creates a new instance of MockBoardSummaryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBoardSummaryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBoardSummaryRepository {
	mock := &MockBoardSummaryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBoardSummaryRepository is an autogenerated mock type for the BoardSummaryRepository type
type MockBoardSummaryRepository struct {
	mock.Mock
}

type MockBoardSummaryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBoardSummaryRepository) EXPECT() *MockBoardSummaryRepository_Expecter {
	return &MockBoardSummaryRepository_Expecter{mock: &_m.Mock}
}

// CalculateSummaryContent provides a mock function for the type MockBoardSummaryRepository
func (_mock *MockBoardSummaryRepository) CalculateSummaryContent(ctx context.Context) (BoardSummaryContent, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CalculateSummaryContent")
	}

	var r0 BoardSummaryContent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (BoardSummaryContent, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) BoardSummaryContent); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(BoardSummaryContent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBoardSummaryRepository_CalculateSummaryContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateSummaryContent'
type MockBoardSummaryRepository_CalculateSummaryContent_Call struct {
	*mock.Call
}

// CalculateSummaryContent is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBoardSummaryRepository_Expecter) CalculateSummaryContent(ctx interface{}) *MockBoardSummaryRepository_CalculateSummaryContent_Call {
	return &MockBoardSummaryRepository_CalculateSummaryContent_Call{Call: _e.mock.On("CalculateSummaryContent", ctx)}
}

func (_c *MockBoardSummaryRepository_CalculateSummaryContent_Call) Run(run func(ctx context.Context)) *MockBoardSummaryRepository_CalculateSummaryContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBoardSummaryRepository_CalculateSummaryContent_Call) Return(boardSummaryContent BoardSummaryContent, err error) *MockBoardSummaryRepository_CalculateSummaryContent_Call {
	_c.Call.Return(boardSummaryContent, err)
	return _c
}

func (_c *MockBoardSummaryRepository_CalculateSummaryContent_Call) RunAndReturn(run func(ctx context.Context) (BoardSummaryContent, error)) *MockBoardSummaryRepository_CalculateSummaryContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestSummary provides a mock function for the type MockBoardSummaryRepository
func (_mock *MockBoardSummaryRepository) GetLatestSummary(ctx context.Context) (BoardSummary, bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSummary")
	}

	var r0 BoardSummary
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (BoardSummary, bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) BoardSummary); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(BoardSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBoardSummaryRepository_GetLatestSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestSummary'
type MockBoardSummaryRepository_GetLatestSummary_Call struct {
	*mock.Call
}

// GetLatestSummary is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBoardSummaryRepository_Expecter) GetLatestSummary(ctx interface{}) *MockBoardSummaryRepository_GetLatestSummary_Call {
	return &MockBoardSummaryRepository_GetLatestSummary_Call{Call: _e.mock.On("GetLatestSummary", ctx)}
}

func (_c *MockBoardSummaryRepository_GetLatestSummary_Call) Run(run func(ctx context.Context)) *MockBoardSummaryRepository_GetLatestSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBoardSummaryRepository_GetLatestSummary_Call) Return(boardSummary BoardSummary, b bool, err error) *MockBoardSummaryRepository_GetLatestSummary_Call {
	_c.Call.Return(boardSummary, b, err)
	return _c
}

func (_c *MockBoardSummaryRepository_GetLatestSummary_Call) RunAndReturn(run func(ctx context.Context) (BoardSummary, bool, error)) *MockBoardSummaryRepository_GetLatestSummary_Call {
	_c.Call.Return(run)
	return _c
}

// StoreSummary provides a mock function for the type MockBoardSummaryRepository
func (_mock *MockBoardSummaryRepository) StoreSummary(ctx context.Context, summary BoardSummary) error {
	ret := _mock.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for StoreSummary")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, BoardSummary) error); ok {
		r0 = returnFunc(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBoardSummaryRepository_StoreSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreSummary'
type MockBoardSummaryRepository_StoreSummary_Call struct {
	*mock.Call
}

// StoreSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - summary BoardSummary
func (_e *MockBoardSummaryRepository_Expecter) StoreSummary(ctx interface{}, summary interface{}) *MockBoardSummaryRepository_StoreSummary_Call {
	return &MockBoardSummaryRepository_StoreSummary_Call{Call: _e.mock.On("StoreSummary", ctx, summary)}
}

func (_c *MockBoardSummaryRepository_StoreSummary_Call) Run(run func(ctx context.Context, summary BoardSummary)) *MockBoardSummaryRepository_StoreSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 BoardSummary
		if args[1] != nil {
			arg1 = args[1].(BoardSummary)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBoardSummaryRepository_StoreSummary_Call) Return(err error) *MockBoardSummaryRepository_StoreSummary_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBoardSummaryRepository_StoreSummary_Call) RunAndReturn(run func(ctx context.Context, summary BoardSummary) error) *MockBoardSummaryRepository_StoreSummary_Call {
	_c.Call.Return(run)
	return _c
}
