// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chat

import (
	"context"

	"github.com/cleitonmarx/symbiont-ai-todoapp/internal/domain/assistant"
	"github.com/cleitonmarx/symbiont-ai-todoapp/internal/domain/outbox"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActionPipeline creates a new instance of MockActionPipeline. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActionPipeline(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActionPipeline {
	mock := &MockActionPipeline{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActionPipeline is an autogenerated mock type for the ActionPipeline type
type MockActionPipeline struct {
	mock.Mock
}

type MockActionPipeline_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActionPipeline) EXPECT() *MockActionPipeline_Expecter {
	return &MockActionPipeline_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockActionPipeline
func (_mock *MockActionPipeline) Handle(ctx context.Context, actionCall assistant.ActionCall, state TurnState, onEvent assistant.EventCallback) (bool, error) {
	ret := _mock.Called(ctx, actionCall, state, onEvent)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, assistant.ActionCall, TurnState, assistant.EventCallback) (bool, error)); ok {
		return returnFunc(ctx, actionCall, state, onEvent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, assistant.ActionCall, TurnState, assistant.EventCallback) bool); ok {
		r0 = returnFunc(ctx, actionCall, state, onEvent)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, assistant.ActionCall, TurnState, assistant.EventCallback) error); ok {
		r1 = returnFunc(ctx, actionCall, state, onEvent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActionPipeline_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockActionPipeline_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - actionCall assistant.ActionCall
//   - state TurnState
//   - onEvent assistant.EventCallback
func (_e *MockActionPipeline_Expecter) Handle(ctx interface{}, actionCall interface{}, state interface{}, onEvent interface{}) *MockActionPipeline_Handle_Call {
	return &MockActionPipeline_Handle_Call{Call: _e.mock.On("Handle", ctx, actionCall, state, onEvent)}
}

func (_c *MockActionPipeline_Handle_Call) Run(run func(ctx context.Context, actionCall assistant.ActionCall, state TurnState, onEvent assistant.EventCallback)) *MockActionPipeline_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 assistant.ActionCall
		if args[1] != nil {
			arg1 = args[1].(assistant.ActionCall)
		}
		var arg2 TurnState
		if args[2] != nil {
			arg2 = args[2].(TurnState)
		}
		var arg3 assistant.EventCallback
		if args[3] != nil {
			arg3 = args[3].(assistant.EventCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockActionPipeline_Handle_Call) Return(b bool, err error) *MockActionPipeline_Handle_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockActionPipeline_Handle_Call) RunAndReturn(run func(ctx context.Context, actionCall assistant.ActionCall, state TurnState, onEvent assistant.EventCallback) (bool, error)) *MockActionPipeline_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConversationCompactor creates a new instance of MockConversationCompactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationCompactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationCompactor {
	mock := &MockConversationCompactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConversationCompactor is an autogenerated mock type for the ConversationCompactor type
type MockConversationCompactor struct {
	mock.Mock
}

type MockConversationCompactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationCompactor) EXPECT() *MockConversationCompactor_Expecter {
	return &MockConversationCompactor_Expecter{mock: &_m.Mock}
}

// Compact provides a mock function for the type MockConversationCompactor
func (_mock *MockConversationCompactor) Compact(ctx context.Context, conversationID uuid.UUID) error {
	ret := _mock.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for Compact")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, conversationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationCompactor_Compact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compact'
type MockConversationCompactor_Compact_Call struct {
	*mock.Call
}

// Compact is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID uuid.UUID
func (_e *MockConversationCompactor_Expecter) Compact(ctx interface{}, conversationID interface{}) *MockConversationCompactor_Compact_Call {
	return &MockConversationCompactor_Compact_Call{Call: _e.mock.On("Compact", ctx, conversationID)}
}

func (_c *MockConversationCompactor_Compact_Call) Run(run func(ctx context.Context, conversationID uuid.UUID)) *MockConversationCompactor_Compact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationCompactor_Compact_Call) Return(err error) *MockConversationCompactor_Compact_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationCompactor_Compact_Call) RunAndReturn(run func(ctx context.Context, conversationID uuid.UUID) error) *MockConversationCompactor_Compact_Call {
	_c.Call.Return(run)
	return _c
}

// EvaluateConversationCompaction provides a mock function for the type MockConversationCompactor
func (_mock *MockConversationCompactor) EvaluateConversationCompaction(ctx context.Context, conversationID uuid.UUID, policy assistant.CompactionPolicy) (assistant.CompactionDecision, error) {
	ret := _mock.Called(ctx, conversationID, policy)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateConversationCompaction")
	}

	var r0 assistant.CompactionDecision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, assistant.CompactionPolicy) (assistant.CompactionDecision, error)); ok {
		return returnFunc(ctx, conversationID, policy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, assistant.CompactionPolicy) assistant.CompactionDecision); ok {
		r0 = returnFunc(ctx, conversationID, policy)
	} else {
		r0 = ret.Get(0).(assistant.CompactionDecision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, assistant.CompactionPolicy) error); ok {
		r1 = returnFunc(ctx, conversationID, policy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationCompactor_EvaluateConversationCompaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateConversationCompaction'
type MockConversationCompactor_EvaluateConversationCompaction_Call struct {
	*mock.Call
}

// EvaluateConversationCompaction is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID uuid.UUID
//   - policy assistant.CompactionPolicy
func (_e *MockConversationCompactor_Expecter) EvaluateConversationCompaction(ctx interface{}, conversationID interface{}, policy interface{}) *MockConversationCompactor_EvaluateConversationCompaction_Call {
	return &MockConversationCompactor_EvaluateConversationCompaction_Call{Call: _e.mock.On("EvaluateConversationCompaction", ctx, conversationID, policy)}
}

func (_c *MockConversationCompactor_EvaluateConversationCompaction_Call) Run(run func(ctx context.Context, conversationID uuid.UUID, policy assistant.CompactionPolicy)) *MockConversationCompactor_EvaluateConversationCompaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 assistant.CompactionPolicy
		if args[2] != nil {
			arg2 = args[2].(assistant.CompactionPolicy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConversationCompactor_EvaluateConversationCompaction_Call) Return(compactionDecision assistant.CompactionDecision, err error) *MockConversationCompactor_EvaluateConversationCompaction_Call {
	_c.Call.Return(compactionDecision, err)
	return _c
}

func (_c *MockConversationCompactor_EvaluateConversationCompaction_Call) RunAndReturn(run func(ctx context.Context, conversationID uuid.UUID, policy assistant.CompactionPolicy) (assistant.CompactionDecision, error)) *MockConversationCompactor_EvaluateConversationCompaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConversationTranscriptWriter creates a new instance of MockConversationTranscriptWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationTranscriptWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationTranscriptWriter {
	mock := &MockConversationTranscriptWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConversationTranscriptWriter is an autogenerated mock type for the ConversationTranscriptWriter type
type MockConversationTranscriptWriter struct {
	mock.Mock
}

type MockConversationTranscriptWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationTranscriptWriter) EXPECT() *MockConversationTranscriptWriter_Expecter {
	return &MockConversationTranscriptWriter_Expecter{mock: &_m.Mock}
}

// RepairTurnTranscript provides a mock function for the type MockConversationTranscriptWriter
func (_mock *MockConversationTranscriptWriter) RepairTurnTranscript(ctx context.Context, conversationID uuid.UUID, turnID uuid.UUID) error {
	ret := _mock.Called(ctx, conversationID, turnID)

	if len(ret) == 0 {
		panic("no return value specified for RepairTurnTranscript")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, conversationID, turnID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationTranscriptWriter_RepairTurnTranscript_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepairTurnTranscript'
type MockConversationTranscriptWriter_RepairTurnTranscript_Call struct {
	*mock.Call
}

// RepairTurnTranscript is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID uuid.UUID
//   - turnID uuid.UUID
func (_e *MockConversationTranscriptWriter_Expecter) RepairTurnTranscript(ctx interface{}, conversationID interface{}, turnID interface{}) *MockConversationTranscriptWriter_RepairTurnTranscript_Call {
	return &MockConversationTranscriptWriter_RepairTurnTranscript_Call{Call: _e.mock.On("RepairTurnTranscript", ctx, conversationID, turnID)}
}

func (_c *MockConversationTranscriptWriter_RepairTurnTranscript_Call) Run(run func(ctx context.Context, conversationID uuid.UUID, turnID uuid.UUID)) *MockConversationTranscriptWriter_RepairTurnTranscript_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConversationTranscriptWriter_RepairTurnTranscript_Call) Return(err error) *MockConversationTranscriptWriter_RepairTurnTranscript_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationTranscriptWriter_RepairTurnTranscript_Call) RunAndReturn(run func(ctx context.Context, conversationID uuid.UUID, turnID uuid.UUID) error) *MockConversationTranscriptWriter_RepairTurnTranscript_Call {
	_c.Call.Return(run)
	return _c
}

// WriteMessage provides a mock function for the type MockConversationTranscriptWriter
func (_mock *MockConversationTranscriptWriter) WriteMessage(ctx context.Context, conversation assistant.Conversation, message assistant.ChatMessage) error {
	ret := _mock.Called(ctx, conversation, message)

	if len(ret) == 0 {
		panic("no return value specified for WriteMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, assistant.Conversation, assistant.ChatMessage) error); ok {
		r0 = returnFunc(ctx, conversation, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationTranscriptWriter_WriteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMessage'
type MockConversationTranscriptWriter_WriteMessage_Call struct {
	*mock.Call
}

// WriteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - conversation assistant.Conversation
//   - message assistant.ChatMessage
func (_e *MockConversationTranscriptWriter_Expecter) WriteMessage(ctx interface{}, conversation interface{}, message interface{}) *MockConversationTranscriptWriter_WriteMessage_Call {
	return &MockConversationTranscriptWriter_WriteMessage_Call{Call: _e.mock.On("WriteMessage", ctx, conversation, message)}
}

func (_c *MockConversationTranscriptWriter_WriteMessage_Call) Run(run func(ctx context.Context, conversation assistant.Conversation, message assistant.ChatMessage)) *MockConversationTranscriptWriter_WriteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 assistant.Conversation
		if args[1] != nil {
			arg1 = args[1].(assistant.Conversation)
		}
		var arg2 assistant.ChatMessage
		if args[2] != nil {
			arg2 = args[2].(assistant.ChatMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConversationTranscriptWriter_WriteMessage_Call) Return(err error) *MockConversationTranscriptWriter_WriteMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationTranscriptWriter_WriteMessage_Call) RunAndReturn(run func(ctx context.Context, conversation assistant.Conversation, message assistant.ChatMessage) error) *MockConversationTranscriptWriter_WriteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteConversation creates a new instance of MockDeleteConversation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteConversation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteConversation {
	mock := &MockDeleteConversation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeleteConversation is an autogenerated mock type for the DeleteConversation type
type MockDeleteConversation struct {
	mock.Mock
}

type MockDeleteConversation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteConversation) EXPECT() *MockDeleteConversation_Expecter {
	return &MockDeleteConversation_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockDeleteConversation
func (_mock *MockDeleteConversation) Execute(ctx context.Context, conversationID uuid.UUID) error {
	ret := _mock.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, conversationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeleteConversation_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockDeleteConversation_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID uuid.UUID
func (_e *MockDeleteConversation_Expecter) Execute(ctx interface{}, conversationID interface{}) *MockDeleteConversation_Execute_Call {
	return &MockDeleteConversation_Execute_Call{Call: _e.mock.On("Execute", ctx, conversationID)}
}

func (_c *MockDeleteConversation_Execute_Call) Run(run func(ctx context.Context, conversationID uuid.UUID)) *MockDeleteConversation_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeleteConversation_Execute_Call) Return(err error) *MockDeleteConversation_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeleteConversation_Execute_Call) RunAndReturn(run func(ctx context.Context, conversationID uuid.UUID) error) *MockDeleteConversation_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerateConversationTitle creates a new instance of MockGenerateConversationTitle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerateConversationTitle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerateConversationTitle {
	mock := &MockGenerateConversationTitle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerateConversationTitle is an autogenerated mock type for the GenerateConversationTitle type
type MockGenerateConversationTitle struct {
	mock.Mock
}

type MockGenerateConversationTitle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerateConversationTitle) EXPECT() *MockGenerateConversationTitle_Expecter {
	return &MockGenerateConversationTitle_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockGenerateConversationTitle
func (_mock *MockGenerateConversationTitle) Execute(ctx context.Context, event outbox.ChatMessageEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbox.ChatMessageEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGenerateConversationTitle_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGenerateConversationTitle_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - event outbox.ChatMessageEvent
func (_e *MockGenerateConversationTitle_Expecter) Execute(ctx interface{}, event interface{}) *MockGenerateConversationTitle_Execute_Call {
	return &MockGenerateConversationTitle_Execute_Call{Call: _e.mock.On("Execute", ctx, event)}
}

func (_c *MockGenerateConversationTitle_Execute_Call) Run(run func(ctx context.Context, event outbox.ChatMessageEvent)) *MockGenerateConversationTitle_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbox.ChatMessageEvent
		if args[1] != nil {
			arg1 = args[1].(outbox.ChatMessageEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerateConversationTitle_Execute_Call) Return(err error) *MockGenerateConversationTitle_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGenerateConversationTitle_Execute_Call) RunAndReturn(run func(ctx context.Context, event outbox.ChatMessageEvent) error) *MockGenerateConversationTitle_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListAvailableModels creates a new instance of MockListAvailableModels. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListAvailableModels(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListAvailableModels {
	mock := &MockListAvailableModels{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListAvailableModels is an autogenerated mock type for the ListAvailableModels type
type MockListAvailableModels struct {
	mock.Mock
}

type MockListAvailableModels_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListAvailableModels) EXPECT() *MockListAvailableModels_Expecter {
	return &MockListAvailableModels_Expecter{mock: &_m.Mock}
}

// Query provides a mock function for the type MockListAvailableModels
func (_mock *MockListAvailableModels) Query(ctx context.Context) ([]assistant.ModelInfo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []assistant.ModelInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]assistant.ModelInfo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []assistant.ModelInfo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]assistant.ModelInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListAvailableModels_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockListAvailableModels_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockListAvailableModels_Expecter) Query(ctx interface{}) *MockListAvailableModels_Query_Call {
	return &MockListAvailableModels_Query_Call{Call: _e.mock.On("Query", ctx)}
}

func (_c *MockListAvailableModels_Query_Call) Run(run func(ctx context.Context)) *MockListAvailableModels_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListAvailableModels_Query_Call) Return(modelInfos []assistant.ModelInfo, err error) *MockListAvailableModels_Query_Call {
	_c.Call.Return(modelInfos, err)
	return _c
}

func (_c *MockListAvailableModels_Query_Call) RunAndReturn(run func(ctx context.Context) ([]assistant.ModelInfo, error)) *MockListAvailableModels_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListAvailableSkills creates a new instance of MockListAvailableSkills. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListAvailableSkills(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListAvailableSkills {
	mock := &MockListAvailableSkills{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListAvailableSkills is an autogenerated mock type for the ListAvailableSkills type
type MockListAvailableSkills struct {
	mock.Mock
}

type MockListAvailableSkills_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListAvailableSkills) EXPECT() *MockListAvailableSkills_Expecter {
	return &MockListAvailableSkills_Expecter{mock: &_m.Mock}
}

// Query provides a mock function for the type MockListAvailableSkills
func (_mock *MockListAvailableSkills) Query(ctx context.Context) ([]assistant.SkillDefinition, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []assistant.SkillDefinition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]assistant.SkillDefinition, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []assistant.SkillDefinition); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]assistant.SkillDefinition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockListAvailableSkills_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockListAvailableSkills_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockListAvailableSkills_Expecter) Query(ctx interface{}) *MockListAvailableSkills_Query_Call {
	return &MockListAvailableSkills_Query_Call{Call: _e.mock.On("Query", ctx)}
}

func (_c *MockListAvailableSkills_Query_Call) Run(run func(ctx context.Context)) *MockListAvailableSkills_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListAvailableSkills_Query_Call) Return(skillDefinitions []assistant.SkillDefinition, err error) *MockListAvailableSkills_Query_Call {
	_c.Call.Return(skillDefinitions, err)
	return _c
}

func (_c *MockListAvailableSkills_Query_Call) RunAndReturn(run func(ctx context.Context) ([]assistant.SkillDefinition, error)) *MockListAvailableSkills_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListChatMessages creates a new instance of MockListChatMessages. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListChatMessages(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListChatMessages {
	mock := &MockListChatMessages{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListChatMessages is an autogenerated mock type for the ListChatMessages type
type MockListChatMessages struct {
	mock.Mock
}

type MockListChatMessages_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListChatMessages) EXPECT() *MockListChatMessages_Expecter {
	return &MockListChatMessages_Expecter{mock: &_m.Mock}
}

// Query provides a mock function for the type MockListChatMessages
func (_mock *MockListChatMessages) Query(ctx context.Context, conversationID uuid.UUID, page int, pageSize int) ([]assistant.ChatMessage, bool, error) {
	ret := _mock.Called(ctx, conversationID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []assistant.ChatMessage
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]assistant.ChatMessage, bool, error)); ok {
		return returnFunc(ctx, conversationID, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []assistant.ChatMessage); ok {
		r0 = returnFunc(ctx, conversationID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]assistant.ChatMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) bool); ok {
		r1 = returnFunc(ctx, conversationID, page, pageSize)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = returnFunc(ctx, conversationID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockListChatMessages_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockListChatMessages_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID uuid.UUID
//   - page int
//   - pageSize int
func (_e *MockListChatMessages_Expecter) Query(ctx interface{}, conversationID interface{}, page interface{}, pageSize interface{}) *MockListChatMessages_Query_Call {
	return &MockListChatMessages_Query_Call{Call: _e.mock.On("Query", ctx, conversationID, page, pageSize)}
}

func (_c *MockListChatMessages_Query_Call) Run(run func(ctx context.Context, conversationID uuid.UUID, page int, pageSize int)) *MockListChatMessages_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockListChatMessages_Query_Call) Return(chatMessages []assistant.ChatMessage, b bool, err error) *MockListChatMessages_Query_Call {
	_c.Call.Return(chatMessages, b, err)
	return _c
}

func (_c *MockListChatMessages_Query_Call) RunAndReturn(run func(ctx context.Context, conversationID uuid.UUID, page int, pageSize int) ([]assistant.ChatMessage, bool, error)) *MockListChatMessages_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListConversations creates a new instance of MockListConversations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListConversations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListConversations {
	mock := &MockListConversations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListConversations is an autogenerated mock type for the ListConversations type
type MockListConversations struct {
	mock.Mock
}

type MockListConversations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListConversations) EXPECT() *MockListConversations_Expecter {
	return &MockListConversations_Expecter{mock: &_m.Mock}
}

// Query provides a mock function for the type MockListConversations
func (_mock *MockListConversations) Query(ctx context.Context, page int, pageSize int) ([]assistant.Conversation, map[uuid.UUID]int64, bool, error) {
	ret := _mock.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []assistant.Conversation
	var r1 map[uuid.UUID]int64
	var r2 bool
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]assistant.Conversation, map[uuid.UUID]int64, bool, error)); ok {
		return returnFunc(ctx, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []assistant.Conversation); ok {
		r0 = returnFunc(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]assistant.Conversation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) map[uuid.UUID]int64); ok {
		r1 = returnFunc(ctx, page, pageSize)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[uuid.UUID]int64)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) bool); ok {
		r2 = returnFunc(ctx, page, pageSize)
	} else {
		r2 = ret.Get(2).(bool)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, int, int) error); ok {
		r3 = returnFunc(ctx, page, pageSize)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockListConversations_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockListConversations_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockListConversations_Expecter) Query(ctx interface{}, page interface{}, pageSize interface{}) *MockListConversations_Query_Call {
	return &MockListConversations_Query_Call{Call: _e.mock.On("Query", ctx, page, pageSize)}
}

func (_c *MockListConversations_Query_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockListConversations_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockListConversations_Query_Call) Return(conversations []assistant.Conversation, uUIDToInt64 map[uuid.UUID]int64, b bool, err error) *MockListConversations_Query_Call {
	_c.Call.Return(conversations, uUIDToInt64, b, err)
	return _c
}

func (_c *MockListConversations_Query_Call) RunAndReturn(run func(ctx context.Context, page int, pageSize int) ([]assistant.Conversation, map[uuid.UUID]int64, bool, error)) *MockListConversations_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStreamChat creates a new instance of MockStreamChat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamChat(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamChat {
	mock := &MockStreamChat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStreamChat is an autogenerated mock type for the StreamChat type
type MockStreamChat struct {
	mock.Mock
}

type MockStreamChat_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamChat) EXPECT() *MockStreamChat_Expecter {
	return &MockStreamChat_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockStreamChat
func (_mock *MockStreamChat) Execute(ctx context.Context, userMessage string, model string, onEvent assistant.EventCallback, opts ...StreamChatOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, userMessage, model, onEvent, opts)
	} else {
		tmpRet = _mock.Called(ctx, userMessage, model, onEvent)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, assistant.EventCallback, ...StreamChatOption) error); ok {
		r0 = returnFunc(ctx, userMessage, model, onEvent, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamChat_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockStreamChat_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userMessage string
//   - model string
//   - onEvent assistant.EventCallback
//   - opts ...StreamChatOption
func (_e *MockStreamChat_Expecter) Execute(ctx interface{}, userMessage interface{}, model interface{}, onEvent interface{}, opts ...interface{}) *MockStreamChat_Execute_Call {
	return &MockStreamChat_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{ctx, userMessage, model, onEvent}, opts...)...)}
}

func (_c *MockStreamChat_Execute_Call) Run(run func(ctx context.Context, userMessage string, model string, onEvent assistant.EventCallback, opts ...StreamChatOption)) *MockStreamChat_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 assistant.EventCallback
		if args[3] != nil {
			arg3 = args[3].(assistant.EventCallback)
		}
		var arg4 []StreamChatOption
		var variadicArgs []StreamChatOption
		if len(args) > 4 {
			variadicArgs = args[4].([]StreamChatOption)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockStreamChat_Execute_Call) Return(err error) *MockStreamChat_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamChat_Execute_Call) RunAndReturn(run func(ctx context.Context, userMessage string, model string, onEvent assistant.EventCallback, opts ...StreamChatOption) error) *MockStreamChat_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubmitActionApproval creates a new instance of MockSubmitActionApproval. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubmitActionApproval(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubmitActionApproval {
	mock := &MockSubmitActionApproval{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubmitActionApproval is an autogenerated mock type for the SubmitActionApproval type
type MockSubmitActionApproval struct {
	mock.Mock
}

type MockSubmitActionApproval_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubmitActionApproval) EXPECT() *MockSubmitActionApproval_Expecter {
	return &MockSubmitActionApproval_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockSubmitActionApproval
func (_mock *MockSubmitActionApproval) Execute(ctx context.Context, input SubmitActionApprovalInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SubmitActionApprovalInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSubmitActionApproval_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSubmitActionApproval_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input SubmitActionApprovalInput
func (_e *MockSubmitActionApproval_Expecter) Execute(ctx interface{}, input interface{}) *MockSubmitActionApproval_Execute_Call {
	return &MockSubmitActionApproval_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockSubmitActionApproval_Execute_Call) Run(run func(ctx context.Context, input SubmitActionApprovalInput)) *MockSubmitActionApproval_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SubmitActionApprovalInput
		if args[1] != nil {
			arg1 = args[1].(SubmitActionApprovalInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSubmitActionApproval_Execute_Call) Return(err error) *MockSubmitActionApproval_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSubmitActionApproval_Execute_Call) RunAndReturn(run func(ctx context.Context, input SubmitActionApprovalInput) error) *MockSubmitActionApproval_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTurnRunner creates a new instance of MockTurnRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTurnRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTurnRunner {
	mock := &MockTurnRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTurnRunner is an autogenerated mock type for the TurnRunner type
type MockTurnRunner struct {
	mock.Mock
}

type MockTurnRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTurnRunner) EXPECT() *MockTurnRunner_Expecter {
	return &MockTurnRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockTurnRunner
func (_mock *MockTurnRunner) Run(ctx context.Context, state TurnState, onEvent assistant.EventCallback) error {
	ret := _mock.Called(ctx, state, onEvent)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, TurnState, assistant.EventCallback) error); ok {
		r0 = returnFunc(ctx, state, onEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTurnRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTurnRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - state TurnState
//   - onEvent assistant.EventCallback
func (_e *MockTurnRunner_Expecter) Run(ctx interface{}, state interface{}, onEvent interface{}) *MockTurnRunner_Run_Call {
	return &MockTurnRunner_Run_Call{Call: _e.mock.On("Run", ctx, state, onEvent)}
}

func (_c *MockTurnRunner_Run_Call) Run(run func(ctx context.Context, state TurnState, onEvent assistant.EventCallback)) *MockTurnRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TurnState
		if args[1] != nil {
			arg1 = args[1].(TurnState)
		}
		var arg2 assistant.EventCallback
		if args[2] != nil {
			arg2 = args[2].(assistant.EventCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTurnRunner_Run_Call) Return(err error) *MockTurnRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTurnRunner_Run_Call) RunAndReturn(run func(ctx context.Context, state TurnState, onEvent assistant.EventCallback) error) *MockTurnRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTurnState creates a new instance of MockTurnState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTurnState(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTurnState {
	mock := &MockTurnState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTurnState is an autogenerated mock type for the TurnState type
type MockTurnState struct {
	mock.Mock
}

type MockTurnState_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTurnState) EXPECT() *MockTurnState_Expecter {
	return &MockTurnState_Expecter{mock: &_m.Mock}
}

// AccumulateTokenUsage provides a mock function for the type MockTurnState
func (_mock *MockTurnState) AccumulateTokenUsage(usage assistant.Usage) {
	_mock.Called(usage)
	return
}

// MockTurnState_AccumulateTokenUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccumulateTokenUsage'
type MockTurnState_AccumulateTokenUsage_Call struct {
	*mock.Call
}

// AccumulateTokenUsage is a helper method to define mock.On call
//   - usage assistant.Usage
func (_e *MockTurnState_Expecter) AccumulateTokenUsage(usage interface{}) *MockTurnState_AccumulateTokenUsage_Call {
	return &MockTurnState_AccumulateTokenUsage_Call{Call: _e.mock.On("AccumulateTokenUsage", usage)}
}

func (_c *MockTurnState_AccumulateTokenUsage_Call) Run(run func(usage assistant.Usage)) *MockTurnState_AccumulateTokenUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 assistant.Usage
		if args[0] != nil {
			arg0 = args[0].(assistant.Usage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTurnState_AccumulateTokenUsage_Call) Return() *MockTurnState_AccumulateTokenUsage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTurnState_AccumulateTokenUsage_Call) RunAndReturn(run func(usage assistant.Usage)) *MockTurnState_AccumulateTokenUsage_Call {
	_c.Run(run)
	return _c
}

// AppendAssistantContent provides a mock function for the type MockTurnState
func (_mock *MockTurnState) AppendAssistantContent(text string) {
	_mock.Called(text)
	return
}

// MockTurnState_AppendAssistantContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendAssistantContent'
type MockTurnState_AppendAssistantContent_Call struct {
	*mock.Call
}

// AppendAssistantContent is a helper method to define mock.On call
//   - text string
func (_e *MockTurnState_Expecter) AppendAssistantContent(text interface{}) *MockTurnState_AppendAssistantContent_Call {
	return &MockTurnState_AppendAssistantContent_Call{Call: _e.mock.On("AppendAssistantContent", text)}
}

func (_c *MockTurnState_AppendAssistantContent_Call) Run(run func(text string)) *MockTurnState_AppendAssistantContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTurnState_AppendAssistantContent_Call) Return() *MockTurnState_AppendAssistantContent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTurnState_AppendAssistantContent_Call) RunAndReturn(run func(text string)) *MockTurnState_AppendAssistantContent_Call {
	_c.Run(run)
	return _c
}

// AppendRequestMessages provides a mock function for the type MockTurnState
func (_mock *MockTurnState) AppendRequestMessages(messages ...assistant.Message) {
	if len(messages) > 0 {
		_mock.Called(messages)
	} else {
		_mock.Called()
	}

	return
}

// MockTurnState_AppendRequestMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendRequestMessages'
type MockTurnState_AppendRequestMessages_Call struct {
	*mock.Call
}

// AppendRequestMessages is a helper method to define mock.On call
//   - messages ...assistant.Message
func (_e *MockTurnState_Expecter) AppendRequestMessages(messages ...interface{}) *MockTurnState_AppendRequestMessages_Call {
	return &MockTurnState_AppendRequestMessages_Call{Call: _e.mock.On("AppendRequestMessages",
		append([]interface{}{}, messages...)...)}
}

func (_c *MockTurnState_AppendRequestMessages_Call) Run(run func(messages ...assistant.Message)) *MockTurnState_AppendRequestMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []assistant.Message
		var variadicArgs []assistant.Message
		if len(args) > 0 {
			variadicArgs = args[0].([]assistant.Message)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockTurnState_AppendRequestMessages_Call) Return() *MockTurnState_AppendRequestMessages_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTurnState_AppendRequestMessages_Call) RunAndReturn(run func(messages ...assistant.Message)) *MockTurnState_AppendRequestMessages_Call {
	_c.Run(run)
	return _c
}

// ApplyRecoveryPolicy provides a mock function for the type MockTurnState
func (_mock *MockTurnState) ApplyRecoveryPolicy(runErr error, maxMessages int) {
	_mock.Called(runErr, maxMessages)
	return
}

// MockTurnState_ApplyRecoveryPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyRecoveryPolicy'
type MockTurnState_ApplyRecoveryPolicy_Call struct {
	*mock.Call
}

// ApplyRecoveryPolicy is a helper method to define mock.On call
//   - runErr error
//   - maxMessages int
func (_e *MockTurnState_Expecter) ApplyRecoveryPolicy(runErr interface{}, maxMessages interface{}) *MockTurnState_ApplyRecoveryPolicy_Call {
	return &MockTurnState_ApplyRecoveryPolicy_Call{Call: _e.mock.On("ApplyRecoveryPolicy", runErr, maxMessages)}
}

func (_c *MockTurnState_ApplyRecoveryPolicy_Call) Run(run func(runErr error, maxMessages int)) *MockTurnState_ApplyRecoveryPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTurnState_ApplyRecoveryPolicy_Call) Return() *MockTurnState_ApplyRecoveryPolicy_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTurnState_ApplyRecoveryPolicy_Call) RunAndReturn(run func(runErr error, maxMessages int)) *MockTurnState_ApplyRecoveryPolicy_Call {
	_c.Run(run)
	return _c
}

// AssistantContent provides a mock function for the type MockTurnState
func (_mock *MockTurnState) AssistantContent() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AssistantContent")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTurnState_AssistantContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssistantContent'
type MockTurnState_AssistantContent_Call struct {
	*mock.Call
}

// AssistantContent is a helper method to define mock.On call
func (_e *MockTurnState_Expecter) AssistantContent() *MockTurnState_AssistantContent_Call {
	return &MockTurnState_AssistantContent_Call{Call: _e.mock.On("AssistantContent")}
}

func (_c *MockTurnState_AssistantContent_Call) Run(run func()) *MockTurnState_AssistantContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTurnState_AssistantContent_Call) Return(s string) *MockTurnState_AssistantContent_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTurnState_AssistantContent_Call) RunAndReturn(run func() string) *MockTurnState_AssistantContent_Call {
	_c.Call.Return(run)
	return _c
}

// Conversation provides a mock function for the type MockTurnState
func (_mock *MockTurnState) Conversation() assistant.Conversation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Conversation")
	}

	var r0 assistant.Conversation
	if returnFunc, ok := ret.Get(0).(func() assistant.Conversation); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(assistant.Conversation)
	}
	return r0
}

// MockTurnState_Conversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Conversation'
type MockTurnState_Conversation_Call struct {
	*mock.Call
}

// Conversation is a helper method to define mock.On call
func (_e *MockTurnState_Expecter) Conversation() *MockTurnState_Conversation_Call {
	return &MockTurnState_Conversation_Call{Call: _e.mock.On("Conversation")}
}

func (_c *MockTurnState_Conversation_Call) Run(run func()) *MockTurnState_Conversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTurnState_Conversation_Call) Return(conversation assistant.Conversation) *MockTurnState_Conversation_Call {
	_c.Call.Return(conversation)
	return _c
}

func (_c *MockTurnState_Conversation_Call) RunAndReturn(run func() assistant.Conversation) *MockTurnState_Conversation_Call {
	_c.Call.Return(run)
	return _c
}

// ConversationCreated provides a mock function for the type MockTurnState
func (_mock *MockTurnState) ConversationCreated() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConversationCreated")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTurnState_ConversationCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConversationCreated'
type MockTurnState_ConversationCreated_Call struct {
	*mock.Call
}

// ConversationCreated is a helper method to define mock.On call
func (_e *MockTurnState_Expecter) ConversationCreated() *MockTurnState_ConversationCreated_Call {
	return &MockTurnState_ConversationCreated_Call{Call: _e.mock.On("ConversationCreated")}
}

func (_c *MockTurnState_ConversationCreated_Call) Run(run func()) *MockTurnState_ConversationCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTurnState_ConversationCreated_Call) Return(b bool) *MockTurnState_ConversationCreated_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTurnState_ConversationCreated_Call) RunAndReturn(run func() bool) *MockTurnState_ConversationCreated_Call {
	_c.Call.Return(run)
	return _c
}

// HasExceededMaxActionCycles provides a mock function for the type MockTurnState
func (_mock *MockTurnState) HasExceededMaxActionCycles() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasExceededMaxActionCycles")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTurnState_HasExceededMaxActionCycles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasExceededMaxActionCycles'
type MockTurnState_HasExceededMaxActionCycles_Call struct {
	*mock.Call
}

// HasExceededMaxActionCycles is a helper method to define mock.On call
func (_e *MockTurnState_Expecter) HasExceededMaxActionCycles() *MockTurnState_HasExceededMaxActionCycles_Call {
	return &MockTurnState_HasExceededMaxActionCycles_Call{Call: _e.mock.On("HasExceededMaxActionCycles")}
}

func (_c *MockTurnState_HasExceededMaxActionCycles_Call) Run(run func()) *MockTurnState_HasExceededMaxActionCycles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTurnState_HasExceededMaxActionCycles_Call) Return(b bool) *MockTurnState_HasExceededMaxActionCycles_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTurnState_HasExceededMaxActionCycles_Call) RunAndReturn(run func() bool) *MockTurnState_HasExceededMaxActionCycles_Call {
	_c.Call.Return(run)
	return _c
}

// HasExceededRepeatedActionCalls provides a mock function for the type MockTurnState
func (_mock *MockTurnState) HasExceededRepeatedActionCalls(functionName string, arguments string) bool {
	ret := _mock.Called(functionName, arguments)

	if len(ret) == 0 {
		panic("no return value specified for HasExceededRepeatedActionCalls")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(functionName, arguments)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTurnState_HasExceededRepeatedActionCalls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasExceededRepeatedActionCalls'
type MockTurnState_HasExceededRepeatedActionCalls_Call struct {
	*mock.Call
}

// HasExceededRepeatedActionCalls is a helper method to define mock.On call
//   - functionName string
//   - arguments string
func (_e *MockTurnState_Expecter) HasExceededRepeatedActionCalls(functionName interface{}, arguments interface{}) *MockTurnState_HasExceededRepeatedActionCalls_Call {
	return &MockTurnState_HasExceededRepeatedActionCalls_Call{Call: _e.mock.On("HasExceededRepeatedActionCalls", functionName, arguments)}
}

func (_c *MockTurnState_HasExceededRepeatedActionCalls_Call) Run(run func(functionName string, arguments string)) *MockTurnState_HasExceededRepeatedActionCalls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTurnState_HasExceededRepeatedActionCalls_Call) Return(b bool) *MockTurnState_HasExceededRepeatedActionCalls_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTurnState_HasExceededRepeatedActionCalls_Call) RunAndReturn(run func(functionName string, arguments string) bool) *MockTurnState_HasExceededRepeatedActionCalls_Call {
	_c.Call.Return(run)
	return _c
}

// Model provides a mock function for the type MockTurnState
func (_mock *MockTurnState) Model() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Model")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTurnState_Model_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Model'
type MockTurnState_Model_Call struct {
	*mock.Call
}

// Model is a helper method to define mock.On call
func (_e *MockTurnState_Expecter) Model() *MockTurnState_Model_Call {
	return &MockTurnState_Model_Call{Call: _e.mock.On("Model")}
}

func (_c *MockTurnState_Model_Call) Run(run func()) *MockTurnState_Model_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTurnState_Model_Call) Return(s string) *MockTurnState_Model_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTurnState_Model_Call) RunAndReturn(run func() string) *MockTurnState_Model_Call {
	_c.Call.Return(run)
	return _c
}

// NextTurnSequence provides a mock function for the type MockTurnState
func (_mock *MockTurnState) NextTurnSequence() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NextTurnSequence")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockTurnState_NextTurnSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextTurnSequence'
type MockTurnState_NextTurnSequence_Call struct {
	*mock.Call
}

// NextTurnSequence is a helper method to define mock.On call
func (_e *MockTurnState_Expecter) NextTurnSequence() *MockTurnState_NextTurnSequence_Call {
	return &MockTurnState_NextTurnSequence_Call{Call: _e.mock.On("NextTurnSequence")}
}

func (_c *MockTurnState_NextTurnSequence_Call) Run(run func()) *MockTurnState_NextTurnSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTurnState_NextTurnSequence_Call) Return(n int64) *MockTurnState_NextTurnSequence_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockTurnState_NextTurnSequence_Call) RunAndReturn(run func() int64) *MockTurnState_NextTurnSequence_Call {
	_c.Call.Return(run)
	return _c
}

// Request provides a mock function for the type MockTurnState
func (_mock *MockTurnState) Request() assistant.TurnRequest {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 assistant.TurnRequest
	if returnFunc, ok := ret.Get(0).(func() assistant.TurnRequest); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(assistant.TurnRequest)
	}
	return r0
}

// MockTurnState_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockTurnState_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
func (_e *MockTurnState_Expecter) Request() *MockTurnState_Request_Call {
	return &MockTurnState_Request_Call{Call: _e.mock.On("Request")}
}

func (_c *MockTurnState_Request_Call) Run(run func()) *MockTurnState_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTurnState_Request_Call) Return(turnRequest assistant.TurnRequest) *MockTurnState_Request_Call {
	_c.Call.Return(turnRequest)
	return _c
}

func (_c *MockTurnState_Request_Call) RunAndReturn(run func() assistant.TurnRequest) *MockTurnState_Request_Call {
	_c.Call.Return(run)
	return _c
}

// SelectedSkills provides a mock function for the type MockTurnState
func (_mock *MockTurnState) SelectedSkills() []assistant.SelectedSkill {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SelectedSkills")
	}

	var r0 []assistant.SelectedSkill
	if returnFunc, ok := ret.Get(0).(func() []assistant.SelectedSkill); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]assistant.SelectedSkill)
		}
	}
	return r0
}

// MockTurnState_SelectedSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectedSkills'
type MockTurnState_SelectedSkills_Call struct {
	*mock.Call
}

// SelectedSkills is a helper method to define mock.On call
func (_e *MockTurnState_Expecter) SelectedSkills() *MockTurnState_SelectedSkills_Call {
	return &MockTurnState_SelectedSkills_Call{Call: _e.mock.On("SelectedSkills")}
}

func (_c *MockTurnState_SelectedSkills_Call) Run(run func()) *MockTurnState_SelectedSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTurnState_SelectedSkills_Call) Return(selectedSkills []assistant.SelectedSkill) *MockTurnState_SelectedSkills_Call {
	_c.Call.Return(selectedSkills)
	return _c
}

func (_c *MockTurnState_SelectedSkills_Call) RunAndReturn(run func() []assistant.SelectedSkill) *MockTurnState_SelectedSkills_Call {
	_c.Call.Return(run)
	return _c
}

// TokenUsage provides a mock function for the type MockTurnState
func (_mock *MockTurnState) TokenUsage() assistant.Usage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TokenUsage")
	}

	var r0 assistant.Usage
	if returnFunc, ok := ret.Get(0).(func() assistant.Usage); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(assistant.Usage)
	}
	return r0
}

// MockTurnState_TokenUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TokenUsage'
type MockTurnState_TokenUsage_Call struct {
	*mock.Call
}

// TokenUsage is a helper method to define mock.On call
func (_e *MockTurnState_Expecter) TokenUsage() *MockTurnState_TokenUsage_Call {
	return &MockTurnState_TokenUsage_Call{Call: _e.mock.On("TokenUsage")}
}

func (_c *MockTurnState_TokenUsage_Call) Run(run func()) *MockTurnState_TokenUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTurnState_TokenUsage_Call) Return(usage assistant.Usage) *MockTurnState_TokenUsage_Call {
	_c.Call.Return(usage)
	return _c
}

func (_c *MockTurnState_TokenUsage_Call) RunAndReturn(run func() assistant.Usage) *MockTurnState_TokenUsage_Call {
	_c.Call.Return(run)
	return _c
}

// TurnID provides a mock function for the type MockTurnState
func (_mock *MockTurnState) TurnID() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TurnID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockTurnState_TurnID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TurnID'
type MockTurnState_TurnID_Call struct {
	*mock.Call
}

// TurnID is a helper method to define mock.On call
func (_e *MockTurnState_Expecter) TurnID() *MockTurnState_TurnID_Call {
	return &MockTurnState_TurnID_Call{Call: _e.mock.On("TurnID")}
}

func (_c *MockTurnState_TurnID_Call) Run(run func()) *MockTurnState_TurnID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTurnState_TurnID_Call) Return(uUID uuid.UUID) *MockTurnState_TurnID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockTurnState_TurnID_Call) RunAndReturn(run func() uuid.UUID) *MockTurnState_TurnID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTurnStateBuilder creates a new instance of MockTurnStateBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTurnStateBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTurnStateBuilder {
	mock := &MockTurnStateBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTurnStateBuilder is an autogenerated mock type for the TurnStateBuilder type
type MockTurnStateBuilder struct {
	mock.Mock
}

type MockTurnStateBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTurnStateBuilder) EXPECT() *MockTurnStateBuilder_Expecter {
	return &MockTurnStateBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockTurnStateBuilder
func (_mock *MockTurnStateBuilder) Build(ctx context.Context, params BuildTurnStateParams) (TurnState, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 TurnState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, BuildTurnStateParams) (TurnState, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, BuildTurnStateParams) TurnState); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(TurnState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, BuildTurnStateParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTurnStateBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockTurnStateBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - ctx context.Context
//   - params BuildTurnStateParams
func (_e *MockTurnStateBuilder_Expecter) Build(ctx interface{}, params interface{}) *MockTurnStateBuilder_Build_Call {
	return &MockTurnStateBuilder_Build_Call{Call: _e.mock.On("Build", ctx, params)}
}

func (_c *MockTurnStateBuilder_Build_Call) Run(run func(ctx context.Context, params BuildTurnStateParams)) *MockTurnStateBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 BuildTurnStateParams
		if args[1] != nil {
			arg1 = args[1].(BuildTurnStateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTurnStateBuilder_Build_Call) Return(turnState TurnState, err error) *MockTurnStateBuilder_Build_Call {
	_c.Call.Return(turnState, err)
	return _c
}

func (_c *MockTurnStateBuilder_Build_Call) RunAndReturn(run func(ctx context.Context, params BuildTurnStateParams) (TurnState, error)) *MockTurnStateBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdateConversation creates a new instance of MockUpdateConversation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateConversation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateConversation {
	mock := &MockUpdateConversation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateConversation is an autogenerated mock type for the UpdateConversation type
type MockUpdateConversation struct {
	mock.Mock
}

type MockUpdateConversation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateConversation) EXPECT() *MockUpdateConversation_Expecter {
	return &MockUpdateConversation_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockUpdateConversation
func (_mock *MockUpdateConversation) Execute(ctx context.Context, conversationID uuid.UUID, title string) (assistant.Conversation, error) {
	ret := _mock.Called(ctx, conversationID, title)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 assistant.Conversation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (assistant.Conversation, error)); ok {
		return returnFunc(ctx, conversationID, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) assistant.Conversation); ok {
		r0 = returnFunc(ctx, conversationID, title)
	} else {
		r0 = ret.Get(0).(assistant.Conversation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, conversationID, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdateConversation_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdateConversation_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID uuid.UUID
//   - title string
func (_e *MockUpdateConversation_Expecter) Execute(ctx interface{}, conversationID interface{}, title interface{}) *MockUpdateConversation_Execute_Call {
	return &MockUpdateConversation_Execute_Call{Call: _e.mock.On("Execute", ctx, conversationID, title)}
}

func (_c *MockUpdateConversation_Execute_Call) Run(run func(ctx context.Context, conversationID uuid.UUID, title string)) *MockUpdateConversation_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUpdateConversation_Execute_Call) Return(conversation assistant.Conversation, err error) *MockUpdateConversation_Execute_Call {
	_c.Call.Return(conversation, err)
	return _c
}

func (_c *MockUpdateConversation_Execute_Call) RunAndReturn(run func(ctx context.Context, conversationID uuid.UUID, title string) (assistant.Conversation, error)) *MockUpdateConversation_Execute_Call {
	_c.Call.Return(run)
	return _c
}
