// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package outbox

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishEvent provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) PublishEvent(ctx context.Context, event Event) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Event) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_PublishEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishEvent'
type MockEventPublisher_PublishEvent_Call struct {
	*mock.Call
}

// PublishEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event Event
func (_e *MockEventPublisher_Expecter) PublishEvent(ctx interface{}, event interface{}) *MockEventPublisher_PublishEvent_Call {
	return &MockEventPublisher_PublishEvent_Call{Call: _e.mock.On("PublishEvent", ctx, event)}
}

func (_c *MockEventPublisher_PublishEvent_Call) Run(run func(ctx context.Context, event Event)) *MockEventPublisher_PublishEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Event
		if args[1] != nil {
			arg1 = args[1].(Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventPublisher_PublishEvent_Call) Return(err error) *MockEventPublisher_PublishEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_PublishEvent_Call) RunAndReturn(run func(ctx context.Context, event Event) error) *MockEventPublisher_PublishEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateChatEvent provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateChatEvent(ctx context.Context, event ChatMessageEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for CreateChatEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ChatMessageEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateChatEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChatEvent'
type MockRepository_CreateChatEvent_Call struct {
	*mock.Call
}

// CreateChatEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event ChatMessageEvent
func (_e *MockRepository_Expecter) CreateChatEvent(ctx interface{}, event interface{}) *MockRepository_CreateChatEvent_Call {
	return &MockRepository_CreateChatEvent_Call{Call: _e.mock.On("CreateChatEvent", ctx, event)}
}

func (_c *MockRepository_CreateChatEvent_Call) Run(run func(ctx context.Context, event ChatMessageEvent)) *MockRepository_CreateChatEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ChatMessageEvent
		if args[1] != nil {
			arg1 = args[1].(ChatMessageEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateChatEvent_Call) Return(err error) *MockRepository_CreateChatEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateChatEvent_Call) RunAndReturn(run func(ctx context.Context, event ChatMessageEvent) error) *MockRepository_CreateChatEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTodoEvent provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateTodoEvent(ctx context.Context, event TodoEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodoEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, TodoEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateTodoEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTodoEvent'
type MockRepository_CreateTodoEvent_Call struct {
	*mock.Call
}

// CreateTodoEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event TodoEvent
func (_e *MockRepository_Expecter) CreateTodoEvent(ctx interface{}, event interface{}) *MockRepository_CreateTodoEvent_Call {
	return &MockRepository_CreateTodoEvent_Call{Call: _e.mock.On("CreateTodoEvent", ctx, event)}
}

func (_c *MockRepository_CreateTodoEvent_Call) Run(run func(ctx context.Context, event TodoEvent)) *MockRepository_CreateTodoEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TodoEvent
		if args[1] != nil {
			arg1 = args[1].(TodoEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateTodoEvent_Call) Return(err error) *MockRepository_CreateTodoEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateTodoEvent_Call) RunAndReturn(run func(ctx context.Context, event TodoEvent) error) *MockRepository_CreateTodoEvent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEvent provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteEvent(ctx context.Context, eventID uuid.UUID) error {
	ret := _mock.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEvent'
type MockRepository_DeleteEvent_Call struct {
	*mock.Call
}

// DeleteEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
func (_e *MockRepository_Expecter) DeleteEvent(ctx interface{}, eventID interface{}) *MockRepository_DeleteEvent_Call {
	return &MockRepository_DeleteEvent_Call{Call: _e.mock.On("DeleteEvent", ctx, eventID)}
}

func (_c *MockRepository_DeleteEvent_Call) Run(run func(ctx context.Context, eventID uuid.UUID)) *MockRepository_DeleteEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteEvent_Call) Return(err error) *MockRepository_DeleteEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteEvent_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID) error) *MockRepository_DeleteEvent_Call {
	_c.Call.Return(run)
	return _c
}

// FetchPendingEvents provides a mock function for the type MockRepository
func (_mock *MockRepository) FetchPendingEvents(ctx context.Context, limit int) ([]Event, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchPendingEvents")
	}

	var r0 []Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]Event, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []Event); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FetchPendingEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPendingEvents'
type MockRepository_FetchPendingEvents_Call struct {
	*mock.Call
}

// FetchPendingEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockRepository_Expecter) FetchPendingEvents(ctx interface{}, limit interface{}) *MockRepository_FetchPendingEvents_Call {
	return &MockRepository_FetchPendingEvents_Call{Call: _e.mock.On("FetchPendingEvents", ctx, limit)}
}

func (_c *MockRepository_FetchPendingEvents_Call) Run(run func(ctx context.Context, limit int)) *MockRepository_FetchPendingEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_FetchPendingEvents_Call) Return(events []Event, err error) *MockRepository_FetchPendingEvents_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockRepository_FetchPendingEvents_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]Event, error)) *MockRepository_FetchPendingEvents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEvent provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateEvent(ctx context.Context, eventID uuid.UUID, status Status, retryCount int, lastError string) error {
	ret := _mock.Called(ctx, eventID, status, retryCount, lastError)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, Status, int, string) error); ok {
		r0 = returnFunc(ctx, eventID, status, retryCount, lastError)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEvent'
type MockRepository_UpdateEvent_Call struct {
	*mock.Call
}

// UpdateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - status Status
//   - retryCount int
//   - lastError string
func (_e *MockRepository_Expecter) UpdateEvent(ctx interface{}, eventID interface{}, status interface{}, retryCount interface{}, lastError interface{}) *MockRepository_UpdateEvent_Call {
	return &MockRepository_UpdateEvent_Call{Call: _e.mock.On("UpdateEvent", ctx, eventID, status, retryCount, lastError)}
}

func (_c *MockRepository_UpdateEvent_Call) Run(run func(ctx context.Context, eventID uuid.UUID, status Status, retryCount int, lastError string)) *MockRepository_UpdateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 Status
		if args[2] != nil {
			arg2 = args[2].(Status)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateEvent_Call) Return(err error) *MockRepository_UpdateEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateEvent_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID, status Status, retryCount int, lastError string) error) *MockRepository_UpdateEvent_Call {
	_c.Call.Return(run)
	return _c
}
