// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package outbox

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRelay creates a new instance of MockRelay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelay(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelay {
	mock := &MockRelay{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRelay is an autogenerated mock type for the Relay type
type MockRelay struct {
	mock.Mock
}

type MockRelay_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelay) EXPECT() *MockRelay_Expecter {
	return &MockRelay_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockRelay
func (_mock *MockRelay) Execute(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRelay_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockRelay_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRelay_Expecter) Execute(ctx interface{}) *MockRelay_Execute_Call {
	return &MockRelay_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockRelay_Execute_Call) Run(run func(ctx context.Context)) *MockRelay_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRelay_Execute_Call) Return(err error) *MockRelay_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRelay_Execute_Call) RunAndReturn(run func(ctx context.Context) error) *MockRelay_Execute_Call {
	_c.Call.Return(run)
	return _c
}
