// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package assistant

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAction creates a new instance of MockAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAction {
	mock := &MockAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAction is an autogenerated mock type for the Action type
type MockAction struct {
	mock.Mock
}

type MockAction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAction) EXPECT() *MockAction_Expecter {
	return &MockAction_Expecter{mock: &_m.Mock}
}

// Definition provides a mock function for the type MockAction
func (_mock *MockAction) Definition() ActionDefinition {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Definition")
	}

	var r0 ActionDefinition
	if returnFunc, ok := ret.Get(0).(func() ActionDefinition); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ActionDefinition)
	}
	return r0
}

// MockAction_Definition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Definition'
type MockAction_Definition_Call struct {
	*mock.Call
}

// Definition is a helper method to define mock.On call
func (_e *MockAction_Expecter) Definition() *MockAction_Definition_Call {
	return &MockAction_Definition_Call{Call: _e.mock.On("Definition")}
}

func (_c *MockAction_Definition_Call) Run(run func()) *MockAction_Definition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAction_Definition_Call) Return(actionDefinition ActionDefinition) *MockAction_Definition_Call {
	_c.Call.Return(actionDefinition)
	return _c
}

func (_c *MockAction_Definition_Call) RunAndReturn(run func() ActionDefinition) *MockAction_Definition_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type MockAction
func (_mock *MockAction) Execute(context1 context.Context, actionCall ActionCall, messages []Message) Message {
	ret := _mock.Called(context1, actionCall, messages)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 Message
	if returnFunc, ok := ret.Get(0).(func(context.Context, ActionCall, []Message) Message); ok {
		r0 = returnFunc(context1, actionCall, messages)
	} else {
		r0 = ret.Get(0).(Message)
	}
	return r0
}

// MockAction_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAction_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - actionCall ActionCall
//   - messages []Message
func (_e *MockAction_Expecter) Execute(context1 interface{}, actionCall interface{}, messages interface{}) *MockAction_Execute_Call {
	return &MockAction_Execute_Call{Call: _e.mock.On("Execute", context1, actionCall, messages)}
}

func (_c *MockAction_Execute_Call) Run(run func(context1 context.Context, actionCall ActionCall, messages []Message)) *MockAction_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ActionCall
		if args[1] != nil {
			arg1 = args[1].(ActionCall)
		}
		var arg2 []Message
		if args[2] != nil {
			arg2 = args[2].([]Message)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAction_Execute_Call) Return(message Message) *MockAction_Execute_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockAction_Execute_Call) RunAndReturn(run func(context1 context.Context, actionCall ActionCall, messages []Message) Message) *MockAction_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Renderer provides a mock function for the type MockAction
func (_mock *MockAction) Renderer() (ActionResultRenderer, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Renderer")
	}

	var r0 ActionResultRenderer
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (ActionResultRenderer, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() ActionResultRenderer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ActionResultRenderer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockAction_Renderer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Renderer'
type MockAction_Renderer_Call struct {
	*mock.Call
}

// Renderer is a helper method to define mock.On call
func (_e *MockAction_Expecter) Renderer() *MockAction_Renderer_Call {
	return &MockAction_Renderer_Call{Call: _e.mock.On("Renderer")}
}

func (_c *MockAction_Renderer_Call) Run(run func()) *MockAction_Renderer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAction_Renderer_Call) Return(actionResultRenderer ActionResultRenderer, b bool) *MockAction_Renderer_Call {
	_c.Call.Return(actionResultRenderer, b)
	return _c
}

func (_c *MockAction_Renderer_Call) RunAndReturn(run func() (ActionResultRenderer, bool)) *MockAction_Renderer_Call {
	_c.Call.Return(run)
	return _c
}

// StatusMessage provides a mock function for the type MockAction
func (_mock *MockAction) StatusMessage() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StatusMessage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAction_StatusMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusMessage'
type MockAction_StatusMessage_Call struct {
	*mock.Call
}

// StatusMessage is a helper method to define mock.On call
func (_e *MockAction_Expecter) StatusMessage() *MockAction_StatusMessage_Call {
	return &MockAction_StatusMessage_Call{Call: _e.mock.On("StatusMessage")}
}

func (_c *MockAction_StatusMessage_Call) Run(run func()) *MockAction_StatusMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAction_StatusMessage_Call) Return(s string) *MockAction_StatusMessage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAction_StatusMessage_Call) RunAndReturn(run func() string) *MockAction_StatusMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActionRegistry creates a new instance of MockActionRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActionRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActionRegistry {
	mock := &MockActionRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActionRegistry is an autogenerated mock type for the ActionRegistry type
type MockActionRegistry struct {
	mock.Mock
}

type MockActionRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActionRegistry) EXPECT() *MockActionRegistry_Expecter {
	return &MockActionRegistry_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockActionRegistry
func (_mock *MockActionRegistry) Execute(context1 context.Context, actionCall ActionCall, messages []Message) Message {
	ret := _mock.Called(context1, actionCall, messages)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 Message
	if returnFunc, ok := ret.Get(0).(func(context.Context, ActionCall, []Message) Message); ok {
		r0 = returnFunc(context1, actionCall, messages)
	} else {
		r0 = ret.Get(0).(Message)
	}
	return r0
}

// MockActionRegistry_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockActionRegistry_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - actionCall ActionCall
//   - messages []Message
func (_e *MockActionRegistry_Expecter) Execute(context1 interface{}, actionCall interface{}, messages interface{}) *MockActionRegistry_Execute_Call {
	return &MockActionRegistry_Execute_Call{Call: _e.mock.On("Execute", context1, actionCall, messages)}
}

func (_c *MockActionRegistry_Execute_Call) Run(run func(context1 context.Context, actionCall ActionCall, messages []Message)) *MockActionRegistry_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ActionCall
		if args[1] != nil {
			arg1 = args[1].(ActionCall)
		}
		var arg2 []Message
		if args[2] != nil {
			arg2 = args[2].([]Message)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockActionRegistry_Execute_Call) Return(message Message) *MockActionRegistry_Execute_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockActionRegistry_Execute_Call) RunAndReturn(run func(context1 context.Context, actionCall ActionCall, messages []Message) Message) *MockActionRegistry_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefinition provides a mock function for the type MockActionRegistry
func (_mock *MockActionRegistry) GetDefinition(actionName string) (ActionDefinition, bool) {
	ret := _mock.Called(actionName)

	if len(ret) == 0 {
		panic("no return value specified for GetDefinition")
	}

	var r0 ActionDefinition
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (ActionDefinition, bool)); ok {
		return returnFunc(actionName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) ActionDefinition); ok {
		r0 = returnFunc(actionName)
	} else {
		r0 = ret.Get(0).(ActionDefinition)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(actionName)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockActionRegistry_GetDefinition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefinition'
type MockActionRegistry_GetDefinition_Call struct {
	*mock.Call
}

// GetDefinition is a helper method to define mock.On call
//   - actionName string
func (_e *MockActionRegistry_Expecter) GetDefinition(actionName interface{}) *MockActionRegistry_GetDefinition_Call {
	return &MockActionRegistry_GetDefinition_Call{Call: _e.mock.On("GetDefinition", actionName)}
}

func (_c *MockActionRegistry_GetDefinition_Call) Run(run func(actionName string)) *MockActionRegistry_GetDefinition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActionRegistry_GetDefinition_Call) Return(actionDefinition ActionDefinition, b bool) *MockActionRegistry_GetDefinition_Call {
	_c.Call.Return(actionDefinition, b)
	return _c
}

func (_c *MockActionRegistry_GetDefinition_Call) RunAndReturn(run func(actionName string) (ActionDefinition, bool)) *MockActionRegistry_GetDefinition_Call {
	_c.Call.Return(run)
	return _c
}

// GetRenderer provides a mock function for the type MockActionRegistry
func (_mock *MockActionRegistry) GetRenderer(actionName string) (ActionResultRenderer, bool) {
	ret := _mock.Called(actionName)

	if len(ret) == 0 {
		panic("no return value specified for GetRenderer")
	}

	var r0 ActionResultRenderer
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (ActionResultRenderer, bool)); ok {
		return returnFunc(actionName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) ActionResultRenderer); ok {
		r0 = returnFunc(actionName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ActionResultRenderer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(actionName)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockActionRegistry_GetRenderer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRenderer'
type MockActionRegistry_GetRenderer_Call struct {
	*mock.Call
}

// GetRenderer is a helper method to define mock.On call
//   - actionName string
func (_e *MockActionRegistry_Expecter) GetRenderer(actionName interface{}) *MockActionRegistry_GetRenderer_Call {
	return &MockActionRegistry_GetRenderer_Call{Call: _e.mock.On("GetRenderer", actionName)}
}

func (_c *MockActionRegistry_GetRenderer_Call) Run(run func(actionName string)) *MockActionRegistry_GetRenderer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActionRegistry_GetRenderer_Call) Return(actionResultRenderer ActionResultRenderer, b bool) *MockActionRegistry_GetRenderer_Call {
	_c.Call.Return(actionResultRenderer, b)
	return _c
}

func (_c *MockActionRegistry_GetRenderer_Call) RunAndReturn(run func(actionName string) (ActionResultRenderer, bool)) *MockActionRegistry_GetRenderer_Call {
	_c.Call.Return(run)
	return _c
}

// StatusMessage provides a mock function for the type MockActionRegistry
func (_mock *MockActionRegistry) StatusMessage(actionName string) string {
	ret := _mock.Called(actionName)

	if len(ret) == 0 {
		panic("no return value specified for StatusMessage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(actionName)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockActionRegistry_StatusMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusMessage'
type MockActionRegistry_StatusMessage_Call struct {
	*mock.Call
}

// StatusMessage is a helper method to define mock.On call
//   - actionName string
func (_e *MockActionRegistry_Expecter) StatusMessage(actionName interface{}) *MockActionRegistry_StatusMessage_Call {
	return &MockActionRegistry_StatusMessage_Call{Call: _e.mock.On("StatusMessage", actionName)}
}

func (_c *MockActionRegistry_StatusMessage_Call) Run(run func(actionName string)) *MockActionRegistry_StatusMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActionRegistry_StatusMessage_Call) Return(s string) *MockActionRegistry_StatusMessage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockActionRegistry_StatusMessage_Call) RunAndReturn(run func(actionName string) string) *MockActionRegistry_StatusMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActionResultRenderer creates a new instance of MockActionResultRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActionResultRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActionResultRenderer {
	mock := &MockActionResultRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActionResultRenderer is an autogenerated mock type for the ActionResultRenderer type
type MockActionResultRenderer struct {
	mock.Mock
}

type MockActionResultRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActionResultRenderer) EXPECT() *MockActionResultRenderer_Expecter {
	return &MockActionResultRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function for the type MockActionResultRenderer
func (_mock *MockActionResultRenderer) Render(actionCall ActionCall, result Message) (Message, bool) {
	ret := _mock.Called(actionCall, result)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 Message
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(ActionCall, Message) (Message, bool)); ok {
		return returnFunc(actionCall, result)
	}
	if returnFunc, ok := ret.Get(0).(func(ActionCall, Message) Message); ok {
		r0 = returnFunc(actionCall, result)
	} else {
		r0 = ret.Get(0).(Message)
	}
	if returnFunc, ok := ret.Get(1).(func(ActionCall, Message) bool); ok {
		r1 = returnFunc(actionCall, result)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockActionResultRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockActionResultRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - actionCall ActionCall
//   - result Message
func (_e *MockActionResultRenderer_Expecter) Render(actionCall interface{}, result interface{}) *MockActionResultRenderer_Render_Call {
	return &MockActionResultRenderer_Render_Call{Call: _e.mock.On("Render", actionCall, result)}
}

func (_c *MockActionResultRenderer_Render_Call) Run(run func(actionCall ActionCall, result Message)) *MockActionResultRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ActionCall
		if args[0] != nil {
			arg0 = args[0].(ActionCall)
		}
		var arg1 Message
		if args[1] != nil {
			arg1 = args[1].(Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActionResultRenderer_Render_Call) Return(rendered Message, ok bool) *MockActionResultRenderer_Render_Call {
	_c.Call.Return(rendered, ok)
	return _c
}

func (_c *MockActionResultRenderer_Render_Call) RunAndReturn(run func(actionCall ActionCall, result Message) (Message, bool)) *MockActionResultRenderer_Render_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActionApprovalDispatcher creates a new instance of MockActionApprovalDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActionApprovalDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActionApprovalDispatcher {
	mock := &MockActionApprovalDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActionApprovalDispatcher is an autogenerated mock type for the ActionApprovalDispatcher type
type MockActionApprovalDispatcher struct {
	mock.Mock
}

type MockActionApprovalDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActionApprovalDispatcher) EXPECT() *MockActionApprovalDispatcher_Expecter {
	return &MockActionApprovalDispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type MockActionApprovalDispatcher
func (_mock *MockActionApprovalDispatcher) Dispatch(ctx context.Context, decision ActionApprovalDecision) bool {
	ret := _mock.Called(ctx, decision)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, ActionApprovalDecision) bool); ok {
		r0 = returnFunc(ctx, decision)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockActionApprovalDispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type MockActionApprovalDispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - decision ActionApprovalDecision
func (_e *MockActionApprovalDispatcher_Expecter) Dispatch(ctx interface{}, decision interface{}) *MockActionApprovalDispatcher_Dispatch_Call {
	return &MockActionApprovalDispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, decision)}
}

func (_c *MockActionApprovalDispatcher_Dispatch_Call) Run(run func(ctx context.Context, decision ActionApprovalDecision)) *MockActionApprovalDispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ActionApprovalDecision
		if args[1] != nil {
			arg1 = args[1].(ActionApprovalDecision)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActionApprovalDispatcher_Dispatch_Call) Return(b bool) *MockActionApprovalDispatcher_Dispatch_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockActionApprovalDispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, decision ActionApprovalDecision) bool) *MockActionApprovalDispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockActionApprovalDispatcher
func (_mock *MockActionApprovalDispatcher) Wait(ctx context.Context, key ActionApprovalKey) (ActionApprovalDecision, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 ActionApprovalDecision
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ActionApprovalKey) (ActionApprovalDecision, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ActionApprovalKey) ActionApprovalDecision); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(ActionApprovalDecision)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ActionApprovalKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActionApprovalDispatcher_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockActionApprovalDispatcher_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
//   - key ActionApprovalKey
func (_e *MockActionApprovalDispatcher_Expecter) Wait(ctx interface{}, key interface{}) *MockActionApprovalDispatcher_Wait_Call {
	return &MockActionApprovalDispatcher_Wait_Call{Call: _e.mock.On("Wait", ctx, key)}
}

func (_c *MockActionApprovalDispatcher_Wait_Call) Run(run func(ctx context.Context, key ActionApprovalKey)) *MockActionApprovalDispatcher_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ActionApprovalKey
		if args[1] != nil {
			arg1 = args[1].(ActionApprovalKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActionApprovalDispatcher_Wait_Call) Return(actionApprovalDecision ActionApprovalDecision, err error) *MockActionApprovalDispatcher_Wait_Call {
	_c.Call.Return(actionApprovalDecision, err)
	return _c
}

func (_c *MockActionApprovalDispatcher_Wait_Call) RunAndReturn(run func(ctx context.Context, key ActionApprovalKey) (ActionApprovalDecision, error)) *MockActionApprovalDispatcher_Wait_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAssistant creates a new instance of MockAssistant. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssistant(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssistant {
	mock := &MockAssistant{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAssistant is an autogenerated mock type for the Assistant type
type MockAssistant struct {
	mock.Mock
}

type MockAssistant_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssistant) EXPECT() *MockAssistant_Expecter {
	return &MockAssistant_Expecter{mock: &_m.Mock}
}

// RunTurn provides a mock function for the type MockAssistant
func (_mock *MockAssistant) RunTurn(ctx context.Context, req TurnRequest, onEvent EventCallback) error {
	ret := _mock.Called(ctx, req, onEvent)

	if len(ret) == 0 {
		panic("no return value specified for RunTurn")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, TurnRequest, EventCallback) error); ok {
		r0 = returnFunc(ctx, req, onEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAssistant_RunTurn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunTurn'
type MockAssistant_RunTurn_Call struct {
	*mock.Call
}

// RunTurn is a helper method to define mock.On call
//   - ctx context.Context
//   - req TurnRequest
//   - onEvent EventCallback
func (_e *MockAssistant_Expecter) RunTurn(ctx interface{}, req interface{}, onEvent interface{}) *MockAssistant_RunTurn_Call {
	return &MockAssistant_RunTurn_Call{Call: _e.mock.On("RunTurn", ctx, req, onEvent)}
}

func (_c *MockAssistant_RunTurn_Call) Run(run func(ctx context.Context, req TurnRequest, onEvent EventCallback)) *MockAssistant_RunTurn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TurnRequest
		if args[1] != nil {
			arg1 = args[1].(TurnRequest)
		}
		var arg2 EventCallback
		if args[2] != nil {
			arg2 = args[2].(EventCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAssistant_RunTurn_Call) Return(err error) *MockAssistant_RunTurn_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAssistant_RunTurn_Call) RunAndReturn(run func(ctx context.Context, req TurnRequest, onEvent EventCallback) error) *MockAssistant_RunTurn_Call {
	_c.Call.Return(run)
	return _c
}

// RunTurnSync provides a mock function for the type MockAssistant
func (_mock *MockAssistant) RunTurnSync(ctx context.Context, req TurnRequest) (TurnResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RunTurnSync")
	}

	var r0 TurnResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, TurnRequest) (TurnResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, TurnRequest) TurnResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(TurnResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, TurnRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAssistant_RunTurnSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunTurnSync'
type MockAssistant_RunTurnSync_Call struct {
	*mock.Call
}

// RunTurnSync is a helper method to define mock.On call
//   - ctx context.Context
//   - req TurnRequest
func (_e *MockAssistant_Expecter) RunTurnSync(ctx interface{}, req interface{}) *MockAssistant_RunTurnSync_Call {
	return &MockAssistant_RunTurnSync_Call{Call: _e.mock.On("RunTurnSync", ctx, req)}
}

func (_c *MockAssistant_RunTurnSync_Call) Run(run func(ctx context.Context, req TurnRequest)) *MockAssistant_RunTurnSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 TurnRequest
		if args[1] != nil {
			arg1 = args[1].(TurnRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAssistant_RunTurnSync_Call) Return(turnResponse TurnResponse, err error) *MockAssistant_RunTurnSync_Call {
	_c.Call.Return(turnResponse, err)
	return _c
}

func (_c *MockAssistant_RunTurnSync_Call) RunAndReturn(run func(ctx context.Context, req TurnRequest) (TurnResponse, error)) *MockAssistant_RunTurnSync_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatMessageRepository creates a new instance of MockChatMessageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatMessageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatMessageRepository {
	mock := &MockChatMessageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatMessageRepository is an autogenerated mock type for the ChatMessageRepository type
type MockChatMessageRepository struct {
	mock.Mock
}

type MockChatMessageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatMessageRepository) EXPECT() *MockChatMessageRepository_Expecter {
	return &MockChatMessageRepository_Expecter{mock: &_m.Mock}
}

// CreateChatMessages provides a mock function for the type MockChatMessageRepository
func (_mock *MockChatMessageRepository) CreateChatMessages(ctx context.Context, messages []ChatMessage) error {
	ret := _mock.Called(ctx, messages)

	if len(ret) == 0 {
		panic("no return value specified for CreateChatMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ChatMessage) error); ok {
		r0 = returnFunc(ctx, messages)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatMessageRepository_CreateChatMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChatMessages'
type MockChatMessageRepository_CreateChatMessages_Call struct {
	*mock.Call
}

// CreateChatMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - messages []ChatMessage
func (_e *MockChatMessageRepository_Expecter) CreateChatMessages(ctx interface{}, messages interface{}) *MockChatMessageRepository_CreateChatMessages_Call {
	return &MockChatMessageRepository_CreateChatMessages_Call{Call: _e.mock.On("CreateChatMessages", ctx, messages)}
}

func (_c *MockChatMessageRepository_CreateChatMessages_Call) Run(run func(ctx context.Context, messages []ChatMessage)) *MockChatMessageRepository_CreateChatMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []ChatMessage
		if args[1] != nil {
			arg1 = args[1].([]ChatMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatMessageRepository_CreateChatMessages_Call) Return(err error) *MockChatMessageRepository_CreateChatMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatMessageRepository_CreateChatMessages_Call) RunAndReturn(run func(ctx context.Context, messages []ChatMessage) error) *MockChatMessageRepository_CreateChatMessages_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteConversationMessages provides a mock function for the type MockChatMessageRepository
func (_mock *MockChatMessageRepository) DeleteConversationMessages(ctx context.Context, conversationID uuid.UUID) error {
	ret := _mock.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConversationMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, conversationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatMessageRepository_DeleteConversationMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConversationMessages'
type MockChatMessageRepository_DeleteConversationMessages_Call struct {
	*mock.Call
}

// DeleteConversationMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID uuid.UUID
func (_e *MockChatMessageRepository_Expecter) DeleteConversationMessages(ctx interface{}, conversationID interface{}) *MockChatMessageRepository_DeleteConversationMessages_Call {
	return &MockChatMessageRepository_DeleteConversationMessages_Call{Call: _e.mock.On("DeleteConversationMessages", ctx, conversationID)}
}

func (_c *MockChatMessageRepository_DeleteConversationMessages_Call) Run(run func(ctx context.Context, conversationID uuid.UUID)) *MockChatMessageRepository_DeleteConversationMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatMessageRepository_DeleteConversationMessages_Call) Return(err error) *MockChatMessageRepository_DeleteConversationMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatMessageRepository_DeleteConversationMessages_Call) RunAndReturn(run func(ctx context.Context, conversationID uuid.UUID) error) *MockChatMessageRepository_DeleteConversationMessages_Call {
	_c.Call.Return(run)
	return _c
}

// ListChatMessages provides a mock function for the type MockChatMessageRepository
func (_mock *MockChatMessageRepository) ListChatMessages(ctx context.Context, conversationID uuid.UUID, page int, pageSize int, options ...ListChatMessagesOption) ([]ChatMessage, bool, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, conversationID, page, pageSize, options)
	} else {
		tmpRet = _mock.Called(ctx, conversationID, page, pageSize)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListChatMessages")
	}

	var r0 []ChatMessage
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, ...ListChatMessagesOption) ([]ChatMessage, bool, error)); ok {
		return returnFunc(ctx, conversationID, page, pageSize, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int, ...ListChatMessagesOption) []ChatMessage); ok {
		r0 = returnFunc(ctx, conversationID, page, pageSize, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ChatMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int, ...ListChatMessagesOption) bool); ok {
		r1 = returnFunc(ctx, conversationID, page, pageSize, options...)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int, ...ListChatMessagesOption) error); ok {
		r2 = returnFunc(ctx, conversationID, page, pageSize, options...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockChatMessageRepository_ListChatMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListChatMessages'
type MockChatMessageRepository_ListChatMessages_Call struct {
	*mock.Call
}

// ListChatMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID uuid.UUID
//   - page int
//   - pageSize int
//   - options ...ListChatMessagesOption
func (_e *MockChatMessageRepository_Expecter) ListChatMessages(ctx interface{}, conversationID interface{}, page interface{}, pageSize interface{}, options ...interface{}) *MockChatMessageRepository_ListChatMessages_Call {
	return &MockChatMessageRepository_ListChatMessages_Call{Call: _e.mock.On("ListChatMessages",
		append([]interface{}{ctx, conversationID, page, pageSize}, options...)...)}
}

func (_c *MockChatMessageRepository_ListChatMessages_Call) Run(run func(ctx context.Context, conversationID uuid.UUID, page int, pageSize int, options ...ListChatMessagesOption)) *MockChatMessageRepository_ListChatMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []ListChatMessagesOption
		var variadicArgs []ListChatMessagesOption
		if len(args) > 4 {
			variadicArgs = args[4].([]ListChatMessagesOption)
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *MockChatMessageRepository_ListChatMessages_Call) Return(chatMessages []ChatMessage, b bool, err error) *MockChatMessageRepository_ListChatMessages_Call {
	_c.Call.Return(chatMessages, b, err)
	return _c
}

func (_c *MockChatMessageRepository_ListChatMessages_Call) RunAndReturn(run func(ctx context.Context, conversationID uuid.UUID, page int, pageSize int, options ...ListChatMessagesOption) ([]ChatMessage, bool, error)) *MockChatMessageRepository_ListChatMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConversationRepository creates a new instance of MockConversationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationRepository {
	mock := &MockConversationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConversationRepository is an autogenerated mock type for the ConversationRepository type
type MockConversationRepository struct {
	mock.Mock
}

type MockConversationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationRepository) EXPECT() *MockConversationRepository_Expecter {
	return &MockConversationRepository_Expecter{mock: &_m.Mock}
}

// CreateConversation provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) CreateConversation(context1 context.Context, s string, conversationTitleSource ConversationTitleSource) (Conversation, error) {
	ret := _mock.Called(context1, s, conversationTitleSource)

	if len(ret) == 0 {
		panic("no return value specified for CreateConversation")
	}

	var r0 Conversation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ConversationTitleSource) (Conversation, error)); ok {
		return returnFunc(context1, s, conversationTitleSource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ConversationTitleSource) Conversation); ok {
		r0 = returnFunc(context1, s, conversationTitleSource)
	} else {
		r0 = ret.Get(0).(Conversation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ConversationTitleSource) error); ok {
		r1 = returnFunc(context1, s, conversationTitleSource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationRepository_CreateConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConversation'
type MockConversationRepository_CreateConversation_Call struct {
	*mock.Call
}

// CreateConversation is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - conversationTitleSource ConversationTitleSource
func (_e *MockConversationRepository_Expecter) CreateConversation(context1 interface{}, s interface{}, conversationTitleSource interface{}) *MockConversationRepository_CreateConversation_Call {
	return &MockConversationRepository_CreateConversation_Call{Call: _e.mock.On("CreateConversation", context1, s, conversationTitleSource)}
}

func (_c *MockConversationRepository_CreateConversation_Call) Run(run func(context1 context.Context, s string, conversationTitleSource ConversationTitleSource)) *MockConversationRepository_CreateConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ConversationTitleSource
		if args[2] != nil {
			arg2 = args[2].(ConversationTitleSource)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConversationRepository_CreateConversation_Call) Return(conversation Conversation, err error) *MockConversationRepository_CreateConversation_Call {
	_c.Call.Return(conversation, err)
	return _c
}

func (_c *MockConversationRepository_CreateConversation_Call) RunAndReturn(run func(context1 context.Context, s string, conversationTitleSource ConversationTitleSource) (Conversation, error)) *MockConversationRepository_CreateConversation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteConversation provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) DeleteConversation(context1 context.Context, uUID uuid.UUID) error {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConversation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationRepository_DeleteConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConversation'
type MockConversationRepository_DeleteConversation_Call struct {
	*mock.Call
}

// DeleteConversation is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockConversationRepository_Expecter) DeleteConversation(context1 interface{}, uUID interface{}) *MockConversationRepository_DeleteConversation_Call {
	return &MockConversationRepository_DeleteConversation_Call{Call: _e.mock.On("DeleteConversation", context1, uUID)}
}

func (_c *MockConversationRepository_DeleteConversation_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockConversationRepository_DeleteConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_DeleteConversation_Call) Return(err error) *MockConversationRepository_DeleteConversation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationRepository_DeleteConversation_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) error) *MockConversationRepository_DeleteConversation_Call {
	_c.Call.Return(run)
	return _c
}

// GetConversation provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) GetConversation(context1 context.Context, uUID uuid.UUID) (Conversation, bool, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for GetConversation")
	}

	var r0 Conversation
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (Conversation, bool, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) Conversation); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Get(0).(Conversation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(context1, uUID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockConversationRepository_GetConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConversation'
type MockConversationRepository_GetConversation_Call struct {
	*mock.Call
}

// GetConversation is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockConversationRepository_Expecter) GetConversation(context1 interface{}, uUID interface{}) *MockConversationRepository_GetConversation_Call {
	return &MockConversationRepository_GetConversation_Call{Call: _e.mock.On("GetConversation", context1, uUID)}
}

func (_c *MockConversationRepository_GetConversation_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockConversationRepository_GetConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_GetConversation_Call) Return(conversation Conversation, b bool, err error) *MockConversationRepository_GetConversation_Call {
	_c.Call.Return(conversation, b, err)
	return _c
}

func (_c *MockConversationRepository_GetConversation_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (Conversation, bool, error)) *MockConversationRepository_GetConversation_Call {
	_c.Call.Return(run)
	return _c
}

// ListConversations provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) ListConversations(ctx context.Context, page int, pageSize int) ([]Conversation, bool, error) {
	ret := _mock.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListConversations")
	}

	var r0 []Conversation
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]Conversation, bool, error)); ok {
		return returnFunc(ctx, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []Conversation); ok {
		r0 = returnFunc(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Conversation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) bool); ok {
		r1 = returnFunc(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockConversationRepository_ListConversations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConversations'
type MockConversationRepository_ListConversations_Call struct {
	*mock.Call
}

// ListConversations is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockConversationRepository_Expecter) ListConversations(ctx interface{}, page interface{}, pageSize interface{}) *MockConversationRepository_ListConversations_Call {
	return &MockConversationRepository_ListConversations_Call{Call: _e.mock.On("ListConversations", ctx, page, pageSize)}
}

func (_c *MockConversationRepository_ListConversations_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockConversationRepository_ListConversations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConversationRepository_ListConversations_Call) Return(conversations []Conversation, b bool, err error) *MockConversationRepository_ListConversations_Call {
	_c.Call.Return(conversations, b, err)
	return _c
}

func (_c *MockConversationRepository_ListConversations_Call) RunAndReturn(run func(ctx context.Context, page int, pageSize int) ([]Conversation, bool, error)) *MockConversationRepository_ListConversations_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConversation provides a mock function for the type MockConversationRepository
func (_mock *MockConversationRepository) UpdateConversation(context1 context.Context, conversation Conversation) error {
	ret := _mock.Called(context1, conversation)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConversation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Conversation) error); ok {
		r0 = returnFunc(context1, conversation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationRepository_UpdateConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConversation'
type MockConversationRepository_UpdateConversation_Call struct {
	*mock.Call
}

// UpdateConversation is a helper method to define mock.On call
//   - context1 context.Context
//   - conversation Conversation
func (_e *MockConversationRepository_Expecter) UpdateConversation(context1 interface{}, conversation interface{}) *MockConversationRepository_UpdateConversation_Call {
	return &MockConversationRepository_UpdateConversation_Call{Call: _e.mock.On("UpdateConversation", context1, conversation)}
}

func (_c *MockConversationRepository_UpdateConversation_Call) Run(run func(context1 context.Context, conversation Conversation)) *MockConversationRepository_UpdateConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Conversation
		if args[1] != nil {
			arg1 = args[1].(Conversation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationRepository_UpdateConversation_Call) Return(err error) *MockConversationRepository_UpdateConversation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationRepository_UpdateConversation_Call) RunAndReturn(run func(context1 context.Context, conversation Conversation) error) *MockConversationRepository_UpdateConversation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConversationSummaryRepository creates a new instance of MockConversationSummaryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationSummaryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationSummaryRepository {
	mock := &MockConversationSummaryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConversationSummaryRepository is an autogenerated mock type for the ConversationSummaryRepository type
type MockConversationSummaryRepository struct {
	mock.Mock
}

type MockConversationSummaryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationSummaryRepository) EXPECT() *MockConversationSummaryRepository_Expecter {
	return &MockConversationSummaryRepository_Expecter{mock: &_m.Mock}
}

// DeleteConversationSummary provides a mock function for the type MockConversationSummaryRepository
func (_mock *MockConversationSummaryRepository) DeleteConversationSummary(ctx context.Context, conversationID uuid.UUID) error {
	ret := _mock.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConversationSummary")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, conversationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationSummaryRepository_DeleteConversationSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConversationSummary'
type MockConversationSummaryRepository_DeleteConversationSummary_Call struct {
	*mock.Call
}

// DeleteConversationSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID uuid.UUID
func (_e *MockConversationSummaryRepository_Expecter) DeleteConversationSummary(ctx interface{}, conversationID interface{}) *MockConversationSummaryRepository_DeleteConversationSummary_Call {
	return &MockConversationSummaryRepository_DeleteConversationSummary_Call{Call: _e.mock.On("DeleteConversationSummary", ctx, conversationID)}
}

func (_c *MockConversationSummaryRepository_DeleteConversationSummary_Call) Run(run func(ctx context.Context, conversationID uuid.UUID)) *MockConversationSummaryRepository_DeleteConversationSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationSummaryRepository_DeleteConversationSummary_Call) Return(err error) *MockConversationSummaryRepository_DeleteConversationSummary_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationSummaryRepository_DeleteConversationSummary_Call) RunAndReturn(run func(ctx context.Context, conversationID uuid.UUID) error) *MockConversationSummaryRepository_DeleteConversationSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetConversationSummary provides a mock function for the type MockConversationSummaryRepository
func (_mock *MockConversationSummaryRepository) GetConversationSummary(ctx context.Context, conversationID uuid.UUID) (ConversationSummary, bool, error) {
	ret := _mock.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for GetConversationSummary")
	}

	var r0 ConversationSummary
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (ConversationSummary, bool, error)); ok {
		return returnFunc(ctx, conversationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ConversationSummary); ok {
		r0 = returnFunc(ctx, conversationID)
	} else {
		r0 = ret.Get(0).(ConversationSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = returnFunc(ctx, conversationID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, conversationID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockConversationSummaryRepository_GetConversationSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConversationSummary'
type MockConversationSummaryRepository_GetConversationSummary_Call struct {
	*mock.Call
}

// GetConversationSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID uuid.UUID
func (_e *MockConversationSummaryRepository_Expecter) GetConversationSummary(ctx interface{}, conversationID interface{}) *MockConversationSummaryRepository_GetConversationSummary_Call {
	return &MockConversationSummaryRepository_GetConversationSummary_Call{Call: _e.mock.On("GetConversationSummary", ctx, conversationID)}
}

func (_c *MockConversationSummaryRepository_GetConversationSummary_Call) Run(run func(ctx context.Context, conversationID uuid.UUID)) *MockConversationSummaryRepository_GetConversationSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationSummaryRepository_GetConversationSummary_Call) Return(conversationSummary ConversationSummary, b bool, err error) *MockConversationSummaryRepository_GetConversationSummary_Call {
	_c.Call.Return(conversationSummary, b, err)
	return _c
}

func (_c *MockConversationSummaryRepository_GetConversationSummary_Call) RunAndReturn(run func(ctx context.Context, conversationID uuid.UUID) (ConversationSummary, bool, error)) *MockConversationSummaryRepository_GetConversationSummary_Call {
	_c.Call.Return(run)
	return _c
}

// StoreConversationSummary provides a mock function for the type MockConversationSummaryRepository
func (_mock *MockConversationSummaryRepository) StoreConversationSummary(ctx context.Context, summary ConversationSummary) error {
	ret := _mock.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for StoreConversationSummary")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ConversationSummary) error); ok {
		r0 = returnFunc(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationSummaryRepository_StoreConversationSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreConversationSummary'
type MockConversationSummaryRepository_StoreConversationSummary_Call struct {
	*mock.Call
}

// StoreConversationSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - summary ConversationSummary
func (_e *MockConversationSummaryRepository_Expecter) StoreConversationSummary(ctx interface{}, summary interface{}) *MockConversationSummaryRepository_StoreConversationSummary_Call {
	return &MockConversationSummaryRepository_StoreConversationSummary_Call{Call: _e.mock.On("StoreConversationSummary", ctx, summary)}
}

func (_c *MockConversationSummaryRepository_StoreConversationSummary_Call) Run(run func(ctx context.Context, summary ConversationSummary)) *MockConversationSummaryRepository_StoreConversationSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ConversationSummary
		if args[1] != nil {
			arg1 = args[1].(ConversationSummary)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationSummaryRepository_StoreConversationSummary_Call) Return(err error) *MockConversationSummaryRepository_StoreConversationSummary_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationSummaryRepository_StoreConversationSummary_Call) RunAndReturn(run func(ctx context.Context, summary ConversationSummary) error) *MockConversationSummaryRepository_StoreConversationSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModelCatalog creates a new instance of MockModelCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModelCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModelCatalog {
	mock := &MockModelCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockModelCatalog is an autogenerated mock type for the ModelCatalog type
type MockModelCatalog struct {
	mock.Mock
}

type MockModelCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModelCatalog) EXPECT() *MockModelCatalog_Expecter {
	return &MockModelCatalog_Expecter{mock: &_m.Mock}
}

// ListModels provides a mock function for the type MockModelCatalog
func (_mock *MockModelCatalog) ListModels(ctx context.Context) ([]ModelCapabilities, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListModels")
	}

	var r0 []ModelCapabilities
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ModelCapabilities, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ModelCapabilities); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ModelCapabilities)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockModelCatalog_ListModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListModels'
type MockModelCatalog_ListModels_Call struct {
	*mock.Call
}

// ListModels is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockModelCatalog_Expecter) ListModels(ctx interface{}) *MockModelCatalog_ListModels_Call {
	return &MockModelCatalog_ListModels_Call{Call: _e.mock.On("ListModels", ctx)}
}

func (_c *MockModelCatalog_ListModels_Call) Run(run func(ctx context.Context)) *MockModelCatalog_ListModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockModelCatalog_ListModels_Call) Return(modelCapabilitiess []ModelCapabilities, err error) *MockModelCatalog_ListModels_Call {
	_c.Call.Return(modelCapabilitiess, err)
	return _c
}

func (_c *MockModelCatalog_ListModels_Call) RunAndReturn(run func(ctx context.Context) ([]ModelCapabilities, error)) *MockModelCatalog_ListModels_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSkillRegistry creates a new instance of MockSkillRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkillRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkillRegistry {
	mock := &MockSkillRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkillRegistry is an autogenerated mock type for the SkillRegistry type
type MockSkillRegistry struct {
	mock.Mock
}

type MockSkillRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkillRegistry) EXPECT() *MockSkillRegistry_Expecter {
	return &MockSkillRegistry_Expecter{mock: &_m.Mock}
}

// ListRelevant provides a mock function for the type MockSkillRegistry
func (_mock *MockSkillRegistry) ListRelevant(ctx context.Context, query SkillQueryContext) []SkillDefinition {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListRelevant")
	}

	var r0 []SkillDefinition
	if returnFunc, ok := ret.Get(0).(func(context.Context, SkillQueryContext) []SkillDefinition); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SkillDefinition)
		}
	}
	return r0
}

// MockSkillRegistry_ListRelevant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRelevant'
type MockSkillRegistry_ListRelevant_Call struct {
	*mock.Call
}

// ListRelevant is a helper method to define mock.On call
//   - ctx context.Context
//   - query SkillQueryContext
func (_e *MockSkillRegistry_Expecter) ListRelevant(ctx interface{}, query interface{}) *MockSkillRegistry_ListRelevant_Call {
	return &MockSkillRegistry_ListRelevant_Call{Call: _e.mock.On("ListRelevant", ctx, query)}
}

func (_c *MockSkillRegistry_ListRelevant_Call) Run(run func(ctx context.Context, query SkillQueryContext)) *MockSkillRegistry_ListRelevant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SkillQueryContext
		if args[1] != nil {
			arg1 = args[1].(SkillQueryContext)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSkillRegistry_ListRelevant_Call) Return(skillDefinitions []SkillDefinition) *MockSkillRegistry_ListRelevant_Call {
	_c.Call.Return(skillDefinitions)
	return _c
}

func (_c *MockSkillRegistry_ListRelevant_Call) RunAndReturn(run func(ctx context.Context, query SkillQueryContext) []SkillDefinition) *MockSkillRegistry_ListRelevant_Call {
	_c.Call.Return(run)
	return _c
}
