// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package semantic

import (
	"context"

	"github.com/cleitonmarx/symbiont-ai-todoapp/internal/domain/assistant"
	"github.com/cleitonmarx/symbiont-ai-todoapp/internal/domain/todo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEncoder creates a new instance of MockEncoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncoder {
	mock := &MockEncoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEncoder is an autogenerated mock type for the Encoder type
type MockEncoder struct {
	mock.Mock
}

type MockEncoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncoder) EXPECT() *MockEncoder_Expecter {
	return &MockEncoder_Expecter{mock: &_m.Mock}
}

// VectorizeQuery provides a mock function for the type MockEncoder
func (_mock *MockEncoder) VectorizeQuery(ctx context.Context, model string, query string) (EmbeddingVector, error) {
	ret := _mock.Called(ctx, model, query)

	if len(ret) == 0 {
		panic("no return value specified for VectorizeQuery")
	}

	var r0 EmbeddingVector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (EmbeddingVector, error)); ok {
		return returnFunc(ctx, model, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) EmbeddingVector); ok {
		r0 = returnFunc(ctx, model, query)
	} else {
		r0 = ret.Get(0).(EmbeddingVector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, model, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncoder_VectorizeQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VectorizeQuery'
type MockEncoder_VectorizeQuery_Call struct {
	*mock.Call
}

// VectorizeQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - query string
func (_e *MockEncoder_Expecter) VectorizeQuery(ctx interface{}, model interface{}, query interface{}) *MockEncoder_VectorizeQuery_Call {
	return &MockEncoder_VectorizeQuery_Call{Call: _e.mock.On("VectorizeQuery", ctx, model, query)}
}

func (_c *MockEncoder_VectorizeQuery_Call) Run(run func(ctx context.Context, model string, query string)) *MockEncoder_VectorizeQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEncoder_VectorizeQuery_Call) Return(embeddingVector EmbeddingVector, err error) *MockEncoder_VectorizeQuery_Call {
	_c.Call.Return(embeddingVector, err)
	return _c
}

func (_c *MockEncoder_VectorizeQuery_Call) RunAndReturn(run func(ctx context.Context, model string, query string) (EmbeddingVector, error)) *MockEncoder_VectorizeQuery_Call {
	_c.Call.Return(run)
	return _c
}

// VectorizeSkillDefinition provides a mock function for the type MockEncoder
func (_mock *MockEncoder) VectorizeSkillDefinition(ctx context.Context, model string, skill assistant.SkillDefinition) (EmbeddingVector, EmbeddingVector, error) {
	ret := _mock.Called(ctx, model, skill)

	if len(ret) == 0 {
		panic("no return value specified for VectorizeSkillDefinition")
	}

	var r0 EmbeddingVector
	var r1 EmbeddingVector
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, assistant.SkillDefinition) (EmbeddingVector, EmbeddingVector, error)); ok {
		return returnFunc(ctx, model, skill)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, assistant.SkillDefinition) EmbeddingVector); ok {
		r0 = returnFunc(ctx, model, skill)
	} else {
		r0 = ret.Get(0).(EmbeddingVector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, assistant.SkillDefinition) EmbeddingVector); ok {
		r1 = returnFunc(ctx, model, skill)
	} else {
		r1 = ret.Get(1).(EmbeddingVector)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, assistant.SkillDefinition) error); ok {
		r2 = returnFunc(ctx, model, skill)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEncoder_VectorizeSkillDefinition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VectorizeSkillDefinition'
type MockEncoder_VectorizeSkillDefinition_Call struct {
	*mock.Call
}

// VectorizeSkillDefinition is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - skill assistant.SkillDefinition
func (_e *MockEncoder_Expecter) VectorizeSkillDefinition(ctx interface{}, model interface{}, skill interface{}) *MockEncoder_VectorizeSkillDefinition_Call {
	return &MockEncoder_VectorizeSkillDefinition_Call{Call: _e.mock.On("VectorizeSkillDefinition", ctx, model, skill)}
}

func (_c *MockEncoder_VectorizeSkillDefinition_Call) Run(run func(ctx context.Context, model string, skill assistant.SkillDefinition)) *MockEncoder_VectorizeSkillDefinition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 assistant.SkillDefinition
		if args[2] != nil {
			arg2 = args[2].(assistant.SkillDefinition)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEncoder_VectorizeSkillDefinition_Call) Return(embeddingVector EmbeddingVector, embeddingVector1 EmbeddingVector, err error) *MockEncoder_VectorizeSkillDefinition_Call {
	_c.Call.Return(embeddingVector, embeddingVector1, err)
	return _c
}

func (_c *MockEncoder_VectorizeSkillDefinition_Call) RunAndReturn(run func(ctx context.Context, model string, skill assistant.SkillDefinition) (EmbeddingVector, EmbeddingVector, error)) *MockEncoder_VectorizeSkillDefinition_Call {
	_c.Call.Return(run)
	return _c
}

// VectorizeTodo provides a mock function for the type MockEncoder
func (_mock *MockEncoder) VectorizeTodo(ctx context.Context, model string, todo1 todo.Todo) (EmbeddingVector, error) {
	ret := _mock.Called(ctx, model, todo1)

	if len(ret) == 0 {
		panic("no return value specified for VectorizeTodo")
	}

	var r0 EmbeddingVector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, todo.Todo) (EmbeddingVector, error)); ok {
		return returnFunc(ctx, model, todo1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, todo.Todo) EmbeddingVector); ok {
		r0 = returnFunc(ctx, model, todo1)
	} else {
		r0 = ret.Get(0).(EmbeddingVector)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, todo.Todo) error); ok {
		r1 = returnFunc(ctx, model, todo1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncoder_VectorizeTodo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VectorizeTodo'
type MockEncoder_VectorizeTodo_Call struct {
	*mock.Call
}

// VectorizeTodo is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - todo1 todo.Todo
func (_e *MockEncoder_Expecter) VectorizeTodo(ctx interface{}, model interface{}, todo1 interface{}) *MockEncoder_VectorizeTodo_Call {
	return &MockEncoder_VectorizeTodo_Call{Call: _e.mock.On("VectorizeTodo", ctx, model, todo1)}
}

func (_c *MockEncoder_VectorizeTodo_Call) Run(run func(ctx context.Context, model string, todo1 todo.Todo)) *MockEncoder_VectorizeTodo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 todo.Todo
		if args[2] != nil {
			arg2 = args[2].(todo.Todo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEncoder_VectorizeTodo_Call) Return(embeddingVector EmbeddingVector, err error) *MockEncoder_VectorizeTodo_Call {
	_c.Call.Return(embeddingVector, err)
	return _c
}

func (_c *MockEncoder_VectorizeTodo_Call) RunAndReturn(run func(ctx context.Context, model string, todo1 todo.Todo) (EmbeddingVector, error)) *MockEncoder_VectorizeTodo_Call {
	_c.Call.Return(run)
	return _c
}
