// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actionregistry

import (
	"context"

	"github.com/cleitonmarx/symbiont-ai-todoapp/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmbeddingActionRegistry creates a new instance of MockEmbeddingActionRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingActionRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingActionRegistry {
	mock := &MockEmbeddingActionRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmbeddingActionRegistry is an autogenerated mock type for the EmbeddingActionRegistry type
type MockEmbeddingActionRegistry struct {
	mock.Mock
}

type MockEmbeddingActionRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingActionRegistry) EXPECT() *MockEmbeddingActionRegistry_Expecter {
	return &MockEmbeddingActionRegistry_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockEmbeddingActionRegistry
func (_mock *MockEmbeddingActionRegistry) Execute(context1 context.Context, assistantActionCall domain.AssistantActionCall, assistantMessages []domain.AssistantMessage) domain.AssistantMessage {
	ret := _mock.Called(context1, assistantActionCall, assistantMessages)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 domain.AssistantMessage
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AssistantActionCall, []domain.AssistantMessage) domain.AssistantMessage); ok {
		r0 = returnFunc(context1, assistantActionCall, assistantMessages)
	} else {
		r0 = ret.Get(0).(domain.AssistantMessage)
	}
	return r0
}

// MockEmbeddingActionRegistry_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockEmbeddingActionRegistry_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - assistantActionCall domain.AssistantActionCall
//   - assistantMessages []domain.AssistantMessage
func (_e *MockEmbeddingActionRegistry_Expecter) Execute(context1 interface{}, assistantActionCall interface{}, assistantMessages interface{}) *MockEmbeddingActionRegistry_Execute_Call {
	return &MockEmbeddingActionRegistry_Execute_Call{Call: _e.mock.On("Execute", context1, assistantActionCall, assistantMessages)}
}

func (_c *MockEmbeddingActionRegistry_Execute_Call) Run(run func(context1 context.Context, assistantActionCall domain.AssistantActionCall, assistantMessages []domain.AssistantMessage)) *MockEmbeddingActionRegistry_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AssistantActionCall
		if args[1] != nil {
			arg1 = args[1].(domain.AssistantActionCall)
		}
		var arg2 []domain.AssistantMessage
		if args[2] != nil {
			arg2 = args[2].([]domain.AssistantMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbeddingActionRegistry_Execute_Call) Return(assistantMessage domain.AssistantMessage) *MockEmbeddingActionRegistry_Execute_Call {
	_c.Call.Return(assistantMessage)
	return _c
}

func (_c *MockEmbeddingActionRegistry_Execute_Call) RunAndReturn(run func(context1 context.Context, assistantActionCall domain.AssistantActionCall, assistantMessages []domain.AssistantMessage) domain.AssistantMessage) *MockEmbeddingActionRegistry_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefinition provides a mock function for the type MockEmbeddingActionRegistry
func (_mock *MockEmbeddingActionRegistry) GetDefinition(actionName string) (domain.AssistantActionDefinition, bool) {
	ret := _mock.Called(actionName)

	if len(ret) == 0 {
		panic("no return value specified for GetDefinition")
	}

	var r0 domain.AssistantActionDefinition
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (domain.AssistantActionDefinition, bool)); ok {
		return returnFunc(actionName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.AssistantActionDefinition); ok {
		r0 = returnFunc(actionName)
	} else {
		r0 = ret.Get(0).(domain.AssistantActionDefinition)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(actionName)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockEmbeddingActionRegistry_GetDefinition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefinition'
type MockEmbeddingActionRegistry_GetDefinition_Call struct {
	*mock.Call
}

// GetDefinition is a helper method to define mock.On call
//   - actionName string
func (_e *MockEmbeddingActionRegistry_Expecter) GetDefinition(actionName interface{}) *MockEmbeddingActionRegistry_GetDefinition_Call {
	return &MockEmbeddingActionRegistry_GetDefinition_Call{Call: _e.mock.On("GetDefinition", actionName)}
}

func (_c *MockEmbeddingActionRegistry_GetDefinition_Call) Run(run func(actionName string)) *MockEmbeddingActionRegistry_GetDefinition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmbeddingActionRegistry_GetDefinition_Call) Return(assistantActionDefinition domain.AssistantActionDefinition, b bool) *MockEmbeddingActionRegistry_GetDefinition_Call {
	_c.Call.Return(assistantActionDefinition, b)
	return _c
}

func (_c *MockEmbeddingActionRegistry_GetDefinition_Call) RunAndReturn(run func(actionName string) (domain.AssistantActionDefinition, bool)) *MockEmbeddingActionRegistry_GetDefinition_Call {
	_c.Call.Return(run)
	return _c
}

// ListEmbeddings provides a mock function for the type MockEmbeddingActionRegistry
func (_mock *MockEmbeddingActionRegistry) ListEmbeddings(ctx context.Context) []ActionEmbedding {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListEmbeddings")
	}

	var r0 []ActionEmbedding
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ActionEmbedding); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ActionEmbedding)
		}
	}
	return r0
}

// MockEmbeddingActionRegistry_ListEmbeddings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEmbeddings'
type MockEmbeddingActionRegistry_ListEmbeddings_Call struct {
	*mock.Call
}

// ListEmbeddings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEmbeddingActionRegistry_Expecter) ListEmbeddings(ctx interface{}) *MockEmbeddingActionRegistry_ListEmbeddings_Call {
	return &MockEmbeddingActionRegistry_ListEmbeddings_Call{Call: _e.mock.On("ListEmbeddings", ctx)}
}

func (_c *MockEmbeddingActionRegistry_ListEmbeddings_Call) Run(run func(ctx context.Context)) *MockEmbeddingActionRegistry_ListEmbeddings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmbeddingActionRegistry_ListEmbeddings_Call) Return(actionEmbeddings []ActionEmbedding) *MockEmbeddingActionRegistry_ListEmbeddings_Call {
	_c.Call.Return(actionEmbeddings)
	return _c
}

func (_c *MockEmbeddingActionRegistry_ListEmbeddings_Call) RunAndReturn(run func(ctx context.Context) []ActionEmbedding) *MockEmbeddingActionRegistry_ListEmbeddings_Call {
	_c.Call.Return(run)
	return _c
}

// ListRelevant provides a mock function for the type MockEmbeddingActionRegistry
func (_mock *MockEmbeddingActionRegistry) ListRelevant(ctx context.Context, userInput string) []domain.AssistantActionDefinition {
	ret := _mock.Called(ctx, userInput)

	if len(ret) == 0 {
		panic("no return value specified for ListRelevant")
	}

	var r0 []domain.AssistantActionDefinition
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.AssistantActionDefinition); ok {
		r0 = returnFunc(ctx, userInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AssistantActionDefinition)
		}
	}
	return r0
}

// MockEmbeddingActionRegistry_ListRelevant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRelevant'
type MockEmbeddingActionRegistry_ListRelevant_Call struct {
	*mock.Call
}

// ListRelevant is a helper method to define mock.On call
//   - ctx context.Context
//   - userInput string
func (_e *MockEmbeddingActionRegistry_Expecter) ListRelevant(ctx interface{}, userInput interface{}) *MockEmbeddingActionRegistry_ListRelevant_Call {
	return &MockEmbeddingActionRegistry_ListRelevant_Call{Call: _e.mock.On("ListRelevant", ctx, userInput)}
}

func (_c *MockEmbeddingActionRegistry_ListRelevant_Call) Run(run func(ctx context.Context, userInput string)) *MockEmbeddingActionRegistry_ListRelevant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmbeddingActionRegistry_ListRelevant_Call) Return(assistantActionDefinitions []domain.AssistantActionDefinition) *MockEmbeddingActionRegistry_ListRelevant_Call {
	_c.Call.Return(assistantActionDefinitions)
	return _c
}

func (_c *MockEmbeddingActionRegistry_ListRelevant_Call) RunAndReturn(run func(ctx context.Context, userInput string) []domain.AssistantActionDefinition) *MockEmbeddingActionRegistry_ListRelevant_Call {
	_c.Call.Return(run)
	return _c
}

// StatusMessage provides a mock function for the type MockEmbeddingActionRegistry
func (_mock *MockEmbeddingActionRegistry) StatusMessage(actionName string) string {
	ret := _mock.Called(actionName)

	if len(ret) == 0 {
		panic("no return value specified for StatusMessage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(actionName)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEmbeddingActionRegistry_StatusMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusMessage'
type MockEmbeddingActionRegistry_StatusMessage_Call struct {
	*mock.Call
}

// StatusMessage is a helper method to define mock.On call
//   - actionName string
func (_e *MockEmbeddingActionRegistry_Expecter) StatusMessage(actionName interface{}) *MockEmbeddingActionRegistry_StatusMessage_Call {
	return &MockEmbeddingActionRegistry_StatusMessage_Call{Call: _e.mock.On("StatusMessage", actionName)}
}

func (_c *MockEmbeddingActionRegistry_StatusMessage_Call) Run(run func(actionName string)) *MockEmbeddingActionRegistry_StatusMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEmbeddingActionRegistry_StatusMessage_Call) Return(s string) *MockEmbeddingActionRegistry_StatusMessage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEmbeddingActionRegistry_StatusMessage_Call) RunAndReturn(run func(actionName string) string) *MockEmbeddingActionRegistry_StatusMessage_Call {
	_c.Call.Return(run)
	return _c
}
