package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// BoardSummary represents a summary of the todo board generated by an LLM.
type BoardSummary struct {
	ID            uuid.UUID
	Content       BoardSummaryContent
	Model         string
	GeneratedAt   time.Time
	SourceVersion int64
}

// BoardSummaryContent holds the content of the board summary.
type BoardSummaryContent struct {
	Counts       TodoStatusCounts `json:"counts"`
	NextUp       []NextUpTodoItem `json:"next_up"`
	Overdue      []string         `json:"overdue"`
	NearDeadline []string         `json:"near_deadline"`
	Summary      string           `json:"summary"`
}

// TodoStatusCounts holds the counts of todos by their status.
type TodoStatusCounts struct {
	Open int `json:"OPEN"`
	Done int `json:"DONE"`
	// If you later add more statuses, add fields here to keep JSON stable.
}

// NextUpTodoItem represents a todo item that is next up to be done.
type NextUpTodoItem struct {
	Title  string `json:"title"`
	Reason string `json:"reason"`
}

// BoardSummaryRepository defines the interface for storing and retrieving board summaries.
type BoardSummaryRepository interface {
	StoreSummary(ctx context.Context, summary BoardSummary) error
	GetLatestSummary(ctx context.Context) (BoardSummary, bool, error)
}
