{{- if .Values.env.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todoapp.secretName" . }}
  labels:
    {{- include "todoapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.env.secrets.keys.llmApiKey }}: {{ default "" .Values.env.secrets.data.llmApiKey | quote }}
  {{ .Values.env.secrets.keys.llmEmbeddingApiKey }}: {{ default "" .Values.env.secrets.data.llmEmbeddingApiKey | quote }}
  {{ .Values.env.secrets.keys.mcpGatewayApiKey }}: {{ default "" .Values.env.secrets.data.mcpGatewayApiKey | quote }}
{{- end }}
