// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLocker creates a new instance of MockLocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocker {
	mock := &MockLocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLocker is an autogenerated mock type for the Locker type
type MockLocker struct {
	mock.Mock
}

type MockLocker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocker) EXPECT() *MockLocker_Expecter {
	return &MockLocker_Expecter{mock: &_m.Mock}
}

// TryLock provides a mock function for the type MockLocker
func (_mock *MockLocker) TryLock(ctx context.Context, key string) (func(), bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for TryLock")
	}

	var r0 func()
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (func(), bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) func()); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockLocker_TryLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryLock'
type MockLocker_TryLock_Call struct {
	*mock.Call
}

// TryLock is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockLocker_Expecter) TryLock(ctx interface{}, key interface{}) *MockLocker_TryLock_Call {
	return &MockLocker_TryLock_Call{Call: _e.mock.On("TryLock", ctx, key)}
}

func (_c *MockLocker_TryLock_Call) Run(run func(ctx context.Context, key string)) *MockLocker_TryLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLocker_TryLock_Call) Return(unlock func(), locked bool, err error) *MockLocker_TryLock_Call {
	_c.Call.Return(unlock, locked, err)
	return _c
}

func (_c *MockLocker_TryLock_Call) RunAndReturn(run func(ctx context.Context, key string) (func(), bool, error)) *MockLocker_TryLock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCurrentTimeProvider creates a new instance of MockCurrentTimeProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCurrentTimeProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCurrentTimeProvider {
	mock := &MockCurrentTimeProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCurrentTimeProvider is an autogenerated mock type for the CurrentTimeProvider type
type MockCurrentTimeProvider struct {
	mock.Mock
}

type MockCurrentTimeProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCurrentTimeProvider) EXPECT() *MockCurrentTimeProvider_Expecter {
	return &MockCurrentTimeProvider_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type MockCurrentTimeProvider
func (_mock *MockCurrentTimeProvider) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockCurrentTimeProvider_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockCurrentTimeProvider_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockCurrentTimeProvider_Expecter) Now() *MockCurrentTimeProvider_Now_Call {
	return &MockCurrentTimeProvider_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockCurrentTimeProvider_Now_Call) Run(run func()) *MockCurrentTimeProvider_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCurrentTimeProvider_Now_Call) Return(time1 time.Time) *MockCurrentTimeProvider_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockCurrentTimeProvider_Now_Call) RunAndReturn(run func() time.Time) *MockCurrentTimeProvider_Now_Call {
	_c.Call.Return(run)
	return _c
}
