// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCurrentTimeProvider creates a new instance of MockCurrentTimeProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCurrentTimeProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCurrentTimeProvider {
	mock := &MockCurrentTimeProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCurrentTimeProvider is an autogenerated mock type for the CurrentTimeProvider type
type MockCurrentTimeProvider struct {
	mock.Mock
}

type MockCurrentTimeProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCurrentTimeProvider) EXPECT() *MockCurrentTimeProvider_Expecter {
	return &MockCurrentTimeProvider_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type MockCurrentTimeProvider
func (_mock *MockCurrentTimeProvider) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockCurrentTimeProvider_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockCurrentTimeProvider_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockCurrentTimeProvider_Expecter) Now() *MockCurrentTimeProvider_Now_Call {
	return &MockCurrentTimeProvider_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockCurrentTimeProvider_Now_Call) Run(run func()) *MockCurrentTimeProvider_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCurrentTimeProvider_Now_Call) Return(time1 time.Time) *MockCurrentTimeProvider_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockCurrentTimeProvider_Now_Call) RunAndReturn(run func() time.Time) *MockCurrentTimeProvider_Now_Call {
	_c.Call.Return(run)
	return _c
}
